//An ingredients API that supplies recipe, ingredients, etc. information
//const unirest = require('unirest')

// /////////////////////////////////Ingredients//////////////////////////////////////

// unirest
//   .get(
//     'https://spoonacular-recipe-food-nutrition-v1.p.rapidapi.com/food/ingredients/autocomplete?number=100&query=crab'
//   )
//   .header(
//     'X-RapidAPI-Key',
//     '182b450be9mshbb5f865d06b280cp1c805bjsn3b4a55f8187c'
//   )
//   .end(function(result) {
//     // Useful members are result.status, result.headers, and result.body

//     console.log(result.status, result.headers)
//     const ingredientsObjectsArray = result.body
//     let ingredients = []

//     ingredientsObjectsArray.forEach(element =>
//       ingredients.push(element['name'])
//     )
//     console.log(ingredients)
//   })

const whatever = require('./test')

let unirestIngredientsStrings = [
  'apple',
  'cabbage',
  'applesauce',
  'apple juice',
  'apple cider',
  'apple jelly',
  'apple butter',
  'apple pie spice',
  'apple pie filling',
  'apple cider vinegar',
  'applewood smoked bacon',
  'red apple',
  'tart apple',
  'gala apple',
  'fuji apple',
  'wood apple',
  'rose apple',
  'star apple',
  'green apple',
  'dried apples',
  'sugar apple',
  'cashew apple',
  'bramley apples',
  'custard apple',
  'braeburn apple',
  'mcintosh apple',
  'pink lady apple',
  'grannysmith apple',
  'red delicious apples',
  'golden delicious apple',
  'beef',
  'beef base',
  'beef broth',
  'beef stock',
  'beef steak',
  'beef gravy',
  'beef bones',
  'beef shank',
  'beef brisket',
  'beef liver',
  'beef franks',
  'beef heart',
  'beef cubes',
  'beef bouillon',
  'beef suet',
  'beef fillet',
  'beef consomme',
  'beef jerky',
  'beef short ribs',
  'beef chuck roast',
  'beef round roast',
  'beef strip loin',
  'beefsteak tomato',
  'beef soup bone',
  'beef bouillon cube',
  'beef top sirloin steak',
  'beef bouillon granules',
  'beef tenderloin steaks',
  'beef shoulder roast',
  'beef ravioli',
  'beef sirloin tip roast',
  'beef-flavor ramen',
  'beef bouillon powder',
  'beef marrow bones',
  'beef patties',
  'beef bone broth',
  'beef kidney',
  'beef stock powder',
  'beefless burger',
  'lean beef',
  'roast beef',
  'mince beef',
  'roast beef deli slices',
  'corned beef',
  'corned beef brisket',
  'ground beef round',
  'cooked beef patty',
  'boneless beef short ribs',
  '85% lean beef',
  '90% lean beef',
  'carrot',
  'carrot juice',
  'carrot tops',
  'carrot quickbread mix',
  'baby carrots',
  'peas and carrots',
  'broccoli carrot cauliflower mix',
  'canned peas and carrots',
  'chicken',
  'cheddar cheese',
  'chickens',
  'chickpea',
  'jalapenos',
  'salsa',
  'garlic',
  'butter',
  'corn',
  'catfish',
  'Paprika',
  'flour',
  'chicken meat',
  'chicken legs',
  'chicken base',
  'chicken broth',
  'chicken stock',
  'chicken wings',
  'chicken fat',
  'chicken breast',
  'chicken thighs',
  'chicken parts',
  'chicken gravy',
  'chicken livers',
  'chickpea flour',
  'chicken feet',
  'chicken strips',
  'chicken sausage',
  'chicken cutlets',
  'chicken bones',
  'chicken bouillon',
  'chicken drumsticks',
  'chicken breast halves',
  'chicken seasoning',
  'chicken leg quarters',
  'chicken drumettes',
  'chicken bouillon granules',
  'chicken bouillon powder',
  'chickpea elbows',
  'chicken giblets',
  'chicken mince',
  'chicken brat',
  'chickpea leaf',
  'chicken hearts',
  'chickpea pasta',
  'chickpea penne',
  'chickpea rotini',
  'chicken schmaltz',
  'chickpea spaghetti',
  'desi chickpea',
  'roast chicken',
  'dried chickpeas',
  'baked chicken breast',
  'chunk chicken',
  'split chickpea',
  'canned chickpeas',
  'buffalo chicken sauce',
  'bone in chicken breast halves',
  'bone in chicken breast',
  'duck',
  'duck fat',
  'duck legs',
  'duck breast',
  'duck eggs',
  'duck livers',
  'bombay duck',
  'muscovy duck',
  'egg',
  'eggnog',
  'egg yolk',
  'eggplant',
  'egg white',
  'egg bread',
  'egg noodles',
  'egg beaters',
  'egg replacer',
  'egg substitute',
  'egg roll wrappers',
  'egg white powder',
  'flax egg',
  'chia egg',
  'duck eggs',
  'baby eggplant',
  'quail eggs',
  'Energ egg replacer',
  'cooked egg noodles',
  'poached eggs',
  'chocolate eggs',
  'hardboiled eggs',
  'flour',
  'flounder',
  'flour tortilla',
  'oat flour',
  'cornflour',
  'rye flour',
  'soy flour',
  'cake flour',
  'rice flour',
  'corn flour',
  'masa flour',
  'teff flour',
  'bread flour',
  'spelt flour',
  'besan flour',
  'durum flour',
  'grahm flour',
  'matzo flour',
  'almond flour',
  'pastry flour',
  'quinoa flour',
  'millet flour',
  'peanut flour',
  'wondra flour',
  'barley flour',
  'coconut flour',
  'tapioca flour',
  'sorghum flour',
  'cassava flour',
  'mustard flour',
  'semolina flour',
  'seasoned flour',
  'hazelnut flour',
  'amaranth flour',
  'chestnut flour',
  'buckwheat flour',
  'arrowroot flour',
  'wholemeal flour',
  'grapeseed flour',
  'unbleached flour',
  'brown rice flour',
  'sweet rice flour',
  'lowfat soy flour',
  'self-rising flour',
  'gluten-free flour',
  'high gluten flour',
  'gluten free flour mix',
  'fat free soy flour',
  'malted barley flour',
  'defatted peanut flour',
  'granola',
  'muesli granola',
  'homemade granola',
  'gluten free granola',
  'ham',
  'deli ham',
  'ham bone',
  'ham hock',
  'diced ham',
  'ham steak',
  'cooked ham',
  'smoked ham',
  'boiled ham',
  'serrano ham',
  'graham flour',
  'hamburger bun',
  'graham wafers',
  'hamburger meat',
  'black forest ham',
  'hamburger helper',
  'hamburger patties',
  'graham cracker crust',
  'graham cracker crumbs',
  'graham cracker square',
  'lean ground hamburger',
  'cooked hamburger patty',
  'low fat graham crackers',
  'whole wheat hamburger bun',
  'sesame seed hamburger bun',
  'gluten free hamburger bun',
  'gluten free graham wafers',
  '90% lean ground hamburger',
  'chocolate graham cracker crumbs',
  'gluten-free graham cracker square',
  'ice',
  'iced tea',
  'ice water',
  'ice cream',
  'iceberg lettuce',
  'ice cream cones',
  'iceberg lettuce leaves',
  'ice cream sandwiches',
  'ice-cold booze',
  'rice',
  'rice wine',
  'rice milk',
  'rice chex',
  'rice flour',
  'rice syrup',
  'rice paper',
  'rice vinegar',
  'rice noodles',
  'rice cakes',
  'rice bran oil',
  'rice bran',
  'rice krispies cereal',
  'rice protein powder',
  'juice',
  'Spice Rub',
  'spice mix',
  'juice of lime',
  'juice of lemon',
  'spice cake mix',
  'juice of orange',
  'rice for risotto',
  'juice and zest of 1 lemon',
  'spice drops',
  'juice of meyer lemon',
  '5 spice powder',
  'allspice',
  'licorice twist',
  'verjuice',
  'allspice berries',
  'wild rice',
  'licorice extract',
  'fudge ice cream topping',
  'bbq spice',
  'white rice',
  'brown rice',
  'clam juice',
  'sushi rice',
  'pear juice',
  'black rice',
  'acai juice',
  'jam',
  'jamon',
  'jamon iberico',
  'fig jam',
  'grape jam',
  'cherry jam',
  'apricot jam',
  'dietetic jam',
  'raspberry jam',
  'blueberry jam',
  'pineapple jam',
  'strawberry jam',
  'blackberry jam',
  'lingonberry jam',
  'dietetic grape jam',
  'dietetic cherry jam',
  'dietetic apricot jam',
  'Onions',
  'Onion',
  'dietetic blueberry jam',
  'dietetic raspberry jam',
  'dietetic strawberry jam',
  'dietetic blackberry jam',
  'kale',
  'lacinato kale',
  'lettuce',
  'lettuce leaf',
  'Cos lettuce',
  'bartlett pear',
  'bibb lettuce',
  'bibb lettuce leaves',
  'lamb lettuce',
  'curly lettuce leaves',
  'curly lettuce',
  'iceberg lettuce leaves',
  'red leaf lettuce',
  'red leaf lettuce leaves',
  'mango',
  'mango puree',
  'mango pulp',
  'mango powder',
  'mango nectar',
  'mango chutney',
  'mango sorbet',
  'mangold',
  'mangosteen',
  'mango extract',
  'dried mango',
  'green mango',
  'nuts',
  'nutmeg',
  'nutella',
  'nut butter',
  'nutritional yeast',
  'nutr-grain cereal',
  'peanut',
  'walnut',
  'peanut oil',
  'walnut oil',
  'peanut sauce',
  'peanut butter',
  'peanut flour',
  'peanut butter cups',
  'peanut butter chips',
  'peanut butter candy',
  'peanut butter cookie mix',
  'coconut',
  'soy nuts',
  'coconut oil',
  'coconut rum',
  'coconut milk',
  'soynut butter',
  'coconut flour',
  'coconut sugar',
  'coconut cream',
  'coconut water',
  'coconut flakes',
  'coconut butter',
  'coconut aminos',
  'coconut extract',
  'coconut meat',
  'coconut vinegar',
  'coconut milk beverage',
  'coconut coffee creamer',
  'coconut milk powder',
  'coconut pecan frosting',
  'chesnut',
  'pine nut',
  'hazelnut',
  'coconut wrap',
  'hazelnut oil',
  'hazelnut meal',
  'hazelnut liqueur',
  'chestnut flour',
  'chestnut mushrooms',
  'hazelnut milk',
  'arecanut',
  'pecan nuts',
  'nutmeg',
  'oil',
  'oil packed tuna',
  'oil cured black olives',
  'oil packed sun dried tomatoes',
  'oil-packed anchovies',
  'oil packed albacore tuna',
  'corn oil',
  'palm oil',
  'hemp oil',
  'flax oil',
  'olive oil',
  'chili oil',
  'salad oil',
  'crab boil',
  'lemon oil',
  'basil oil',
  'olive oil cooking spray',
  'plant oil',
  'sesame oil',
  'peanut oil',
  'walnut oil',
  'garlic oil',
  'almond oil',
  'orange oil',
  'coconut oil',
  'avocado oil',
  'truffle oil',
  'mustard oil',
  'hazelnut oil',
  'london broil',
  'grapeseed oil',
  'sunflower oil',
  'safflower oil',
  'rice bran oil',
  'pistachio oil',
  'vegetable oil spread',
  'vegetable oil shortening',
  'lite olive oil',
  'vegetable oil cooking spray',
  'dark sesame oil',
  'virgin olive oil',
  'packaged no-boil lasagna noodles',
  'extravirgin olive oil',
  'parsley',
  'parsnip',
  'parsley flakes',
  'japanese parsley',
  'quinoa',
  'quince',
  'quinoa flour',
  'quinoa flakes',
  'quick cooking oats',
  'quick cooking grits',
  'quick cooking tapioca',
  'quick cooking barley',
  'quinoa pasta',
  'quick-cooking white rice',
  'quick-cooking brown rice',
  'black quinoa',
  'cooked quinoa',
  'carrot quickbread mix',
  'cooked quick oats',
  'cooked quick grits',
  'cooked quick-cooking brown rice',
  'mint',
  'dill',
  'sage',
  'peas',
  'corn',
  'figs',
  'basil',
  'thyme',
  'herbs',
  'fruit',
  'ginger',
  'chives',
  'yeast',
  'nutmeg',
  'parsley',
  'tuna',
  'pasta',
  'ricotta',
  'cilantro',
  'rosemary',
  'tarragon',
  'marjoram',
  'bay leaf',
  'mushrooms',
  'mozzarella',
  'chorizo',
  'green beans',
  'corn kernels',
  'bean sprouts',
  'horseradish',
  'sardines',
  'lavender',
  'epazote',
  'shiitake mushrooms',
  'pasta dough',
  'lasagne sheets',
  'anchovies',
  'fenugreek leaves',
  'herring',
  'tamarind',
  'spaghettini',
  'bulk chorizo',
  'greens',
  'green tea',
  'green peas',
  'green onion',
  'green beans',
  'green chili',
  'green apple',
  'green salsa',
  'green olives',
  'green grapes',
  'green cabbage',
  'green peppers',
  'green tomato',
  'green papaya',
  'green mango',
  'green grams',
  'green tea bags',
  'green food color',
  'green curry paste',
  'green prawns',
  'green cardamoms',
  'green peppercorns',
  'green tea powder',
  'green leaf lettuce',
  'green pesto',
  'green enchilada sauce',
  'green hot sauce',
  'green leaf lettuce leaves',
  'green seedless grapes',
  'green olives with pimentos',
  'beet greens',
  'microgreens',
  'dried green lentils',
  'turnip greens',
  'dried green peas',
  'canned green chiles',
  'cooked green lentils',
  'radish greens',
  'carrot greens',
  'collard greens',
  'mustard greens',
  'cowpea green beans',
  'pickled green beans',
  'chicory greens',
  'pumpkin greens',
  'skinned green gram',
  'dandelion greens',
  'sunflower greens',
  'fiddlehead greens',
  'french style green beans',
  'ramen',
  'caramel',
  'caramel sauce',
  'Caramel Corn',
  'caramelized onions',
  'cooked ramen noodles',
  'beef-flavor ramen',
  'dulce de leche caramel sauce',
  'chocolate covered caramel candy',
  'rice',
  'ricotta',
  'rice wine',
  'rice milk',
  'rice chex',
  'rice flour',
  'rice syrup',
  'rice paper',
  'rice vinegar',
  'rice noodles',
  'rice cakes',
  'rice bran oil',
  'rice bran',
  'rice krispies cereal',
  'rice protein powder',
  'rice for risotto',
  'citric acid',
  'tumeric',
  'wild rice',
  'skim ricotta cheese',
  'white rice',
  'brown rice',
  'sushi rice',
  'black rice',
  'mini ricecakes',
  'turmeric paste',
  'brown rice flour',
  'sweet rice flour',
  'crisp rice cereal',
  'brown rice noodles',
  'crisp rice',
  'cooked rice',
  'minute rice',
  'sticky rice',
  'cooked rice noodles',
  'lowfat ricotta cheese',
  'basmati rice',
  'jasmine rice',
  'miracle rice',
  'non-caloric sweetener',
  'seasoned rice vinegar',
  'glutinous rice',
  'short grain rice',
  'cooked wild rice',
  'cauliflower rice',
  'short brown rice',
  'cooked brown rice',
  'cooked sushi rice',
  'medium grain rice',
  'brown minute rice',
  'salt',
  'salsa',
  'salmon',
  'salami',
  'saltines',
  'salt cod',
  'salad mix',
  'salad oil',
  'salt pork',
  'salsa verde',
  'salmon roe',
  'salted butter',
  'salmon steaks',
  'salad dressing',
  'salted peanuts',
  'salt and pepper',
  'salted cashews',
  'salt packed anchovy',
  'salad shell',
  'salted pork fat',
  'salted sweet butter',
  'no salt added diced tomatoes',
  'sea salt',
  'low salt chicken broth',
  'rock salt',
  'can salmon',
  'fine salt',
  'onion salt',
  'pasta salad mix',
  'ranch salad dressing',
  'asian salad dressing',
  'ranch salad dressing mix',
  'light salad dressing',
  'kosher salt',
  'coarse salt',
  'garlic salt',
  'celery salt',
  'smoked salmon',
  'potato salad',
  'rocket salad',
  'caesar salad dressing',
  'ricotta salata',
  'italian salad dressing mix',
  'roasted salted sunflower nuts',
  'seasoned salt',
  'roasted salted pepitas',
  'catalina salad dressing',
  'raw spiced salmon',
  'vinaigrette salad dressing',
  'dry roasted salted sunflower nuts',
  'tuna',
  'tuna in olive oil',
  'tuna packed in water',
  'ahi tuna',
  'light tuna',
  'fresh tuna',
  'canned tuna',
  'albacore tuna in water',
  'albacore tuna in vegetable oil',
  'yellowfin tuna',
  'unsalted butter',
  'unbleached flour',
  'unsalted peanuts',
  'unsweetened cocoa',
  'unbaked pie shell',
  'unsweetened coconut',
  'unsalted pistachios',
  'unsulfured molasses',
  'unsweetened chocolate',
  'unpopped popcorn',
  'unsweetened applesauce',
  'unseasoned rice vinegar',
  'unsmoked back bacon',
  'unsweetened coconut milk',
  'unsweetened soy milk',
  'unsweetened shredded coconut',
  'unbleached all purpose flour',
  'unsalted pumpkin seeds',
  'unprocessed wheat bran',
  'unsweetened dutch process cocoa powder',
  'uncooked shrimp',
  'sun dried tomato',
  'unsalted sweet butter',
  'sun butter',
  'sun dried tomato pesto',
  'sun dried tomato paste',
  'sun dried tomatoes packed in oil',
  'cajun spice',
  'cajun recipe stewed tomatoes',
  'mesclun',
  'sub bun',
  'brat bun',
  'mini bun',
  'burger bun',
  'hotdog bun',
  'potato bun',
  'pretzel bun',
  'brioche bun',
  'sandwich bun',
  'cinnamon bun',
  'hawaiian bun',
  'ciabatta bun',
  'whole wheat bun',
  'store-bought, uniced cupcakes',
  'gluten free hotdog bun',
  'gluten-free burger bun',
  'whole wheat hotdog bun',
  'vegetable',
  'vegeta',
  'vegenaise',
  'vegan cheese',
  'vegetable oil',
  'veggie patty',
  'vegetable broth',
  'vegetable juice',
  'vegan margarine',
  'vegetarian bacon',
  'veggie lunch meat',
  'vegan sour cream',
  'vegetable shortening',
  'vegan cream cheese',
  'vegan chocolate chips',
  'vegetable stock cube',
  'vegetable oil spread',
  'veggie crumbles',
  'vegan buttery sticks',
  'vegan cheddar cheese',
  'vegetarian baked beans',
  'vegetarian parmesan-style cheese',
  'vegetarian sausages',
  'veggie nuggets',
  'vegan mozzarella',
  'vegetarian sausage',
  'vegetarian meatballs',
  'vegetable tortellini',
  'vegemite',
  'veggie sausage patties',
  'vegetable cooking spray',
  'sea vegetable',
  'root vegetables',
  'asian vegetables',
  'leafy vegetable',
  'textured vegetable protein',
  'butter flavor vegetable shortening',
  'albacore tuna in vegetable oil',
  'wine',
  'wrap',
  'water',
  'wings',
  'wasabi',
  'walnut',
  'wakame',
  'whisky',
  'wieners',
  'wild rice',
  'whole egg',
  'wax beans',
  'whole milk',
  'white wine',
  'white rice',
  'watercress',
  'watermelon',
  'wheat germ',
  'walnut oil',
  'wheat bran',
  'white miso',
  'whitefish',
  'white sugar',
  'white onion',
  'white bread',
  'wood apple',
  'white flour',
  'white corn',
  'white beans',
  'wax chili',
  'wheat chex',
  'wax gourd',
  'white pepper',
  'wine vinegar',
  'wheat beer',
  'whole garlic',
  'wasabi paste',
  'whole turkey',
  'white vinegar',
  'whipped cream',
  'whole chicken',
  'whole cloves',
  'whole almonds',
  'winter squash',
  'wasabi powder',
  'white cheddar',
  'wheat berries',
  'waxy potatoes',
  'white cabbage',
  'wasabi peas',
  'xylitol',
  'xanthan gum',
  'yam',
  'yolk',
  'yuca',
  'yuzu',
  'yeast',
  'yogurt',
  'yukon gold',
  'yuzu juice',
  'yellow onion',
  'yellow miso',
  'yellow squash',
  'yellow mustard',
  'yellow peppers',
  'yellow cornmeal',
  'yellow cake mix',
  'yacon syrup',
  'yellow tomato',
  'yellowfin tuna',
  'young coconut',
  'yard long beans',
  'yellow split peas',
  'yellow wax beans',
  'yellow food color',
  'yellow mustard seeds',
  'yellow cherry tomatoes',
  'yellow curry paste',
  'young coconut meat',
  'yeast rolls',
  'yeast extract spread',
  'yellowtail snapper',
  'yellow corn flour',
  'yuba',
  'yam bean',
  'yuca harina',
  'yellow spice drops',
  'soy yogurt',
  'gf yellow cake mix',
  'food yeast',
  'skim yogurt',
  'greek yogurt',
  'plain yogurt',
  'fresh yeast',
  'sweet yellow onion',
  'lowfat yogurt',
  'frozen yogurt',
  'instant yeast',
  'vanilla yogurt',
  'cooked yellow split peas',
  'brewers yeast',
  'strawberry yogurt',
  'ziti',
  "za'atar",
  'zucchini',
  'zinfandel',
  'zucchini noodles',
  'zest of 1 lemon',
  'zest of 1 orange',
  'zero calorie sweetener',
  'zest and juice of 1 lemon',
  'lime zest',
  'baby zucchini',
  'white zinfandel',
  'cooked ziti',
  'canned zucchini',
  'shiratake ziti',
  'grapefruit zest',
  'blood orange zest',
  'fish',
  'fish sauce',
  'fish stock',
  'fish seasoning',
  'catfish',
  'codfish',
  'redfish',
  'crawfish',
  'monkfish',
  'rockfish',
  'bluefish',
  'goldfish crackers',
  'swordfish',
  'whitefish',
  'monkfish cheeks',
  'thai fish sauce',
  'sablefish',
  'wild fish',
  'carp fish',
  'cuttlefish',
  'ribbon fish',
  'canned fish',
  'tengra fish',
  'Salt Codfish',
  'mackerel fish',
  'pangasius fish',
  'farm raised catfish fillets',
  'herbs',
  'herbes de provence',
  'sherbet',
  'fresh herbs',
  'dried herbs',
  'italian herbs',
  'boursin herb cheese',
  'dill',
  'dill seed',
  'dill pickle',
  'dill pickle relish',
  'dill pickle juice',
  'dill pickle chips',
  'dilly beans',
  'Quesadilla Queso Cheese',
  'granadilla',
  'dried dill',
  'red wine',
  'red miso',
  'red onion',
  'red chile',
  'red apple',
  'red beet',
  'red beans',
  'red plums',
  'red grapes',
  'red hots',
  'red pepper',
  'red potato',
  'red cabbage',
  'red lentils',
  'red snapper',
  'red chard',
  'red jalapeno',
  'red currants',
  'red food color',
  'red curry paste',
  'red grapefruit',
  'red mullet',
  'red wine vinegar',
  'redfish',
  'red bean paste',
  'red chili powder',
  'red chili flakes',
  'red pesto',
  'reduced fat mayo',
  'red leaf lettuce',
  'red pepper powder',
  'red currant jelly',
  'red pepper paste',
  'reduced fat milk',
  'reduced fat cheese',
  'red pearl onions',
  'red enchilada sauce',
  'red delicious apples',
  'red velvet cake mix',
  'reduced fat ice cream',
  'reduced sodium soy sauce',
  'red zinfandel',
  'reduced fat cream cheese',
  'reduced sodium broth',
  'reduced sodium chicken broth',
  'red grapefruit juice',
  'red leaf lettuce leaves',
  'reduced fat shredded cheddar cheese',
  'red-skinned sweet potatoes',
  'red belgian endive',
  'black tea',
  'blackberry',
  'black beans',
  'black rice',
  'black pepper',
  'black olives',
  'black vinegar',
  'blackberry jam',
  'black grapes',
  'black eyed peas',
  'black plums',
  'black walnuts',
  'black tea bags',
  'black cardamoms',
  'black bean sauce',
  'black peppercorns',
  'black quinoa',
  'black treacle',
  'black cod',
  'black forest ham',
  'black lentils',
  'black sesame seeds',
  'black mustard seeds',
  'black cherries',
  'black currants',
  'blackened seasoning',
  'black licorice',
  'blackberry juice',
  'black bass',
  'black drum',
  'black chickpeas',
  'black nightshade',
  'black tiger shrimp',
  'raw black beans',
  'canned black beans',
  'dried blackeye peas',
  'canned black-eyed peas',
  'cooked black lentils',
  'cooked black rice',
  'chinese black mushrooms',
  'salt and black pepper',
  'oil cured black olives',
  'dietetic blackberry jam',
  'fermented black beans',
  'yellow onion',
  'yellow miso',
  'yellow squash',
  'yellow mustard',
  'yellow peppers',
  'yellow cornmeal',
  'yellow cake mix',
  'yellow tomato',
  'yellowfin tuna',
  'yellow split peas',
  'yellow wax beans',
  'yellow food color',
  'yellow mustard seeds',
  'yellow cherry tomatoes',
  'yellow curry paste',
  'yellowtail snapper',
  'yellow corn flour',
  'yellow spice drops',
  'gf yellow cake mix',
  'sweet yellow onion',
  'cooked yellow split peas',
  'blueberry',
  'blue cheese',
  'bluefish',
  'blueberry jam',
  'blue cheese dressing',
  'blue cheese crumbles',
  'blue food coloring',
  'blueberry pie filling',
  'blueberry juice',
  'blueberry jelly',
  'blueberry bagel',
  'wild blueberries',
  'dried blueberries',
  'stilton blue cheese',
  'dietetic blueberry jam',
  'dietetic blueberry jelly',
  'white wine',
  'white rice',
  'white miso',
  'whitefish',
  'white sugar',
  'white onion',
  'white bread',
  'white flour',
  'white corn',
  'white beans',
  'white pepper',
  'white vinegar',
  'white cheddar',
  'white cabbage',
  'white cake mix',
  'white potatoes',
  'white chocolate',
  'white mushrooms',
  'white cornmeal',
  'white grapes',
  'white wine vinegar',
  'white peppercorns',
  'white grape juice',
  'white sesame seeds',
  'white morsels',
  'white asparagus',
  'white balsamic vinegar',
  'white corn tortillas',
  'white whole wheat flour',
  'white salt',
  'white grapefruit',
  'white kidney beans',
  'white sweet potatoes',
  'white zinfandel',
  'white ipa',
  'whitebait',
  'white lentils',
  'white pomfret',
  'white cherries',
  'white seedless grapes',
  'eggwhites',
  'gf white cake mix',
  'egg white powder',
  'solid white tuna packed in water',
  'solid white albacore tuna in olive oil',
  'dried white beans',
  'cooked white rice',
  'canned white beans',
  'dried white kidney beans',
  'canned white kidney beans',
  'orange',
  'orange zest',
  'orange juice',
  'orange oil',
  'orange roughy',
  'orange pepper',
  'orange liqueur',
  'orange bitters',
  'orange gelatin',
  'orange marmalade',
  'orange sections',
  'orange blossom water',
  'orange food coloring',
  'orange juice concentrate',
  'orange tomatoes',
  'navel orange',
  'blood orange',
  'blood orange juice',
  'blood orange zest',
  'candied orange peel',
  'mandarin oranges',
  'mandarin orange segments',
  'red flesh navel orange',
  'potato',
  'potato chips',
  'potato starch',
  'potato flakes',
  'potato buns',
  'potato salad',
  'potato gnocchi',
  'potato bread',
  'potato hash',
  'potato puffs',
  'potato leaves',
  'red potato',
  'new potato',
  'waxy potatoes',
  'gold potatoes',
  'sweet potato',
  'white potatoes',
  'idaho potatoes',
  'sweet potato puree',
  'sweet potato starch noodles',
  'sweet potato leaf',
  'purple potatoes',
  'cream of potato soup',
  'fingerling potatoes',
  'white sweet potatoes',
  'french fried potatoes',
  'red-skinned sweet potatoes',
  'cooked hash browned potatoes',
  'tomato',
  'tomato soup',
  'tomato paste',
  'tomato sauce',
  'tomato puree',
  'tomato juice',
  'tomato ketchup',
  'tomatoes in juice',
  'tomato & basil sauce',
  'tomato pesto',
  'tomato slices',
  'plum tomato',
  'roma tomato',
  'tree tomato',
  'green tomato',
  'grape tomatoes',
  'dried tomatoes',
  'diced tomatoes with green chilies',
  'cherry tomato',
  'canned tomato',
  'stewed tomatoes',
  'yellow tomato',
  'petite tomatoes',
  'orange tomatoes',
  'crushed tomatoes',
  'sundried tomato wrap',
  'sundried tomato paste',
  'beefsteak tomato',
  'sundried tomatoes packed in oil',
  'can diced tomatoes',
  'can whole tomatoes',
  'fire-roasted tomatoes',
  'less sodium tomato soup',
  'cajun stewed tomatoes',
  'yellow cherry tomatoes',
  'no salt added diced tomatoes',
  'banana',
  'banana chips',
  'banana bread',
  'banana leaves',
  'banana peppers',
  'banana liqueur',
  'banana flower',
  'banana shallots',
  'banana pepper rings',
  'banana squash',
  'mashed bananas',
  'squash',
  'squash flowers',
  'gem squash',
  'kuri squash',
  'acorn squash',
  'yellow squash',
  'winter squash',
  'banana squash',
  'cushaw squash',
  'kabocha squash',
  'chayote squash',
  'hubbard squash',
  'scallop squash',
  'zucchini squash',
  'delicata squash',
  'dumpling squash',
  'butternut squash',
  'spaghetti squash',
  'buttercup squash',
  'jarrahdale squash',
  'pumpkin',
  'pumpkin puree',
  'pumpkin seeds',
  'pumpkin pie mix',
  'pumpkin pie spice',
  'pumpernickel',
  'pumpkin spice pudding mix',
  'pumpkin leaf',
  'pumpkin flowers',
  'raw pumpkin seeds',
  'kuri pumpkin',
  'cheese pumpkin',
  'cushaw pumpkin',
  'roasted pumpkin seeds',
  'unsalted pumpkin seeds',
  'butternut pumpkin',
  'jarrahdale pumpkin',
  'basil',
  'basil pesto',
  'basil oil',
  'thai basil',
  'dried basil',
  'lemon basil',
  'tomato & basil sauce',
  'lemon',
  'lemonade',
  'lemon zest',
  'lemongrass',
  'lemon curd',
  'lemon oil',
  'lemon juice',
  'lemon wedge',
  'lemon thyme',
  'lemon balm',
  'lemon pepper',
  'lemon extract',
  'lemon jell-o',
  'lemon basil',
  'lemon lime pop',
  'lemon sole',
  'lemon cake mix',
  'lemon sorbet',
  'lemonade mix',
  'lemon pie filling',
  'lemon pudding mix',
  'lemonade concentrate',
  'lemon sugar',
  'lemon liqueur',
  'lemon essence',
  'meyer lemon',
  'meyer lemon juice',
  'preserved lemon',
  'lime',
  'limeade',
  'lime zest',
  'lime curd',
  'lime juice',
  'lime wedge',
  'lime jell-o',
  'lime leaves',
  'lime gelatin',
  'limeade concentrate',
  'lime slice',
  'lemon lime pop',
  'grape',
  'grapefruit',
  'grape juice',
  'grape jelly',
  'grape leaves',
  'grapeseed oil',
  'grape tomatoes',
  'grapefruit juice',
  'grapefruit zest',
  'grape-nuts cereal',
  'grape seed flour',
  'red grapefruit',
  'green grapes',
  'black grapes',
  'white grape juice',
  'white grapefruit',
  'concord grapes',
  'dietetic grape jam',
  'dietetic grape jelly',
  'muscadine grapes',
  'white seedless grapes',
  'rosemary',
  'rose hips',
  'rosewater',
  'roselle',
  'rosebud',
  'rose apple',
  'sucrose',
  'fresh rosemary',
  'juice',
  'juice of lime',
  'juice of lemon',
  'juice of orange',
  'juice and zest of 1 lemon',
  'juice of meyer lemon',
  'verjuice',
  'pear juice',
  'acai juice',
  'yuzu juice',
  'aloe juice',
  'apple juice',
  'grape juice',
  'fruit juice',
  'guava juice',
  'tomato juice',
  'cherry juice',
  'carrot juice',
  'ginger juice',
  'pickle juice',
  'orange juice concentrate',
  'tangelo juice',
  'tamarind juice',
  'pineapple juice',
  'cranberry juice',
  'vegetable juice',
  'tangerine juice',
  'blueberry juice',
  'cranberry juice cocktail',
  'cranberry juice concentrate',
  'grapefruit juice',
  'clementine juice',
  'blackberry juice',
  'pomegranate juice',
  'white grape juice',
  'tomatoes in juice',
  'pineapple in juice',
  'blood orange juice',
  'passionfruit juice',
  'evaporated cane juice',
  'turkey',
  'turkey meat',
  'turkey neck',
  'turkey bacon',
  'turkey stock',
  'turkey legs',
  'turkey broth',
  'turkey gravy',
  'turkey breast',
  'turkey fat',
  'turkey wings',
  'turkey thighs',
  'turkey sausage',
  'turkey burgers',
  'turkey cutlets',
  'turkey kielbasa',
  'turkey pepperoni',
  'turkey giblets',
  'turkey deli meat',
  'turkey liver',
  'turkey meatballs',
  'turkey tenderloins',
  'turkey pastrami',
  'turkey smokies',
  'turkey heart',
  'turkey bratwurst',
  'turkey berry',
  'turkey gizzards',
  'turkey deli slices',
  'ground turkey',
  'italian turkey sausage',
  'bone in turkey breast',
  '93% lean turkey',
  'leftover turkey',
  'bone in skin on turkey breast',
  'boneless skin-on turkey breast',
  'skinless boneless turkey breast',
  'ground all white meat turkey',
  'kamut',
  'cooked kamut',
  'pork',
  'pork fat',
  'pork loin',
  'pork butt',
  'pork ribs',
  'pork chop',
  'pork belly',
  'pork roast',
  'pork skins',
  'pork links',
  'pork mince',
  'pork bones',
  'pork shoulder',
  'pork liver',
  'pork cutlets',
  'pork stock',
  'pork spareribs',
  'pork and beans',
  'pork tenderloin',
  'pork loin chops',
  'pork shank',
  'pork rub',
  'pork rib roast',
  'pork hocks',
  'pork sausage roll',
  'pork baby back ribs',
  'pork sirloin tip roast',
  'pork fatback',
  'pork broth',
  'pork escalopes',
  'pork kielbasa',
  'pork shoulder joint',
  'pork kidney',
  'pork slices',
  'pork knuckle',
  'pork belly slice',
  'salt pork',
  'lean pork tenderloin',
  'lean pork loin chops',
  'pulled pork',
  'salted pork fat',
  'bone-in pork chops',
  'bone in pork loin',
  'boneless pork shoulder',
  'boneless pork rib roast',
  'lean bone-in pork chops',
  'country style pork ribs',
  'goat milk',
  'goat cheese',
  'bread',
  'breadcrumb',
  'bread bowl',
  'bread flour',
  'bread cubes',
  'bread dough',
  'bread soda',
  'bread machine yeast',
  'breadstick dough',
  'breadfruit',
  'rye bread',
  'cornbread',
  'flatbread',
  'egg bread',
  'cornbread mix',
  'pitabread',
  'naan bread',
  'shortbread',
  'crispbread',
  'white bread',
  'panko breadcrumbs',
  'toast bread',
  'french bread',
  'crusty bread',
  'rustic bread',
  'banana bread',
  'raisin bread',
  'lavash bread',
  'potato bread',
  'paratha bread',
  'ciabatta bread',
  'Hawaiian bread',
  'seasoned bread crumbs',
  'grissini breadsticks',
  'sourdough bread',
  'wheat flatbreads',
  'wholemeal bread',
  'gluten free bread',
  'whole wheat bread crumbs',
  'gluten free breadcrumbs',
  'carrot quickbread mix',
  'pumpernickel bread',
  'gluten free bread flour',
  'sprouted grain bread',
  'wholemeal pitta bread',
  'gluten-free cornbread mix',
  'gluten-free shortbread',
  'gluten-free panko breadcrumbs',
  'gluten-free french bread',
  'milk',
  'milk powder',
  'milk chocolate',
  'milky way',
  'milk substitute',
  'milk kefir',
  'milk chocolate chips',
  'milk chocolate wafers',
  'soymilk',
  '1% milk',
  '2% milk',
  'oat milk',
  'hempmilk',
  'skim milk',
  'rice milk',
  'goat milk',
  'soy milk creamer',
  'skim milk yogurt',
  'skim milk ricotta',
  'skim milk greek yogurt',
  'skim milk mozzarella',
  'skim milk powder',
  'buttermilk',
  'almondmilk',
  'cashewmilk',
  'skim milk parmesan',
  'buttermilk biscuits',
  'buttermilk powder',
  'whole milk mozzarella',
  'malted milk',
  'malted milk balls',
  'whole milk plain yogurt',
  'sheeps milk cheese',
  'coconut milk',
  'coconut milk beverage',
  'coconut milk powder',
  'hazelnut milk',
  'condensed milk',
  'chocolate milk',
  'evaporated milk',
  'chocolate milk powder',
  'skim buttermilk',
  'cultured soymilk',
  'lite coconut milk',
  '1% chocolate milk',
  '2% chocolate milk',
  'low fat buttermilk',
  '2% evaporated milk',
  'canned coconut milk',
  'unsweetened soymilk',
  'condensed skim milk',
  'evaporated skim milk',
  'hersheys kisses brand milk chocolate',
  'lowfat sweetened condensed milk',
  'cheese',
  'cheese soup',
  'cheese curd',
  'cheese dip',
  'cheese ravioli',
  'cheese tortellini',
  'cheesecake mix',
  'cheese tortilla chips',
  'cheese sticks',
  'cheesecake pudding mix',
  'cheeseburger macaroni',
  'cheese pumpkin',
  'cheese shredded',
  'cheese soft cream',
  'soy cheese',
  'feta cheese',
  'goat cheese',
  'blue cheese',
  'jack cheese',
  'brie cheese',
  'taco cheese',
  'edam cheese',
  'dry cheese tortelini',
  'blue cheese dressing',
  'blue cheese crumbles',
  'livercheese',
  'cream cheese',
  'swiss cheese',
  'gouda cheese',
  'colby cheese',
  'grill cheese',
  'pizza cheese',
  'mac & cheese',
  'comte cheese',
  'cream cheese block',
  'nacho cheese sauce',
  'cream cheese frosting',
  'anejo cheese',
  'sheep cheese',
  'quark cheese',
  'romano cheese',
  'asiago cheese',
  'cotija cheese',
  'paneer cheese',
  'oaxaca cheese',
  'farmer cheese',
  'lowfat cheese',
  'cooked cheese tortellini',
  'frozen cheesecake',
  'halumi cheese',
  'cheddar cheese',
  'ricotta cheese',
  'gruyere cheese',
  'cottage cheese',
  'fontina cheese',
  'mexican cheese',
  'havarti cheese',
  'boursin cheese',
  'stilton cheese',
  'burrata cheese',
  'pimento cheese spread',
  'munster cheese',
  'nabulsi cheese',
  'parmesan cheese',
  'american cheese',
  'manchego cheese',
  'velveeta cheese',
  'muenster cheese',
  'taleggio cheese',
  'cheshire cheese',
  '2% swiss cheese',
  'provolone cheese',
  'jarlsberg cheese',
  'roquefort cheese',
  'camembert cheese',
  'Foofoo',
  'mozarella cheese',
  'mascapone cheese',
  'gorgonzola cheese',
  'neufchatel cheese',
  'pepperjack cheese',
  'cheez whiz cheese dip',
  'mozzarella cheese balls',
  'lancashire cheese',
  'quesadilla cheese',
  'light cream cheese',
  'vegan cream cheese',
  'sugar-free cheesecake pudding mix',
  'queso fresco cheese',
  'whole wheat cheese ravioli',
  'grana padano cheese',
  'skim cottage cheese',
  'skim ricotta cheese',
  'sharp cheddar cheese',
  'white cheddar cheese',
  'vegan cheddar cheese',
  'lowfat ricotta cheese',
  'grated cheddar cheese',
  'low fat cottage cheese',
  'grated parmesan cheese',
  'lowfat parmesan cheese',
  'yogurt',
  'soy yogurt',
  'skim yogurt',
  'greek yogurt',
  'plain yogurt',
  'olive oil',
  'lowfat yogurt',
  'frozen yogurt',
  'vanilla yogurt',
  'strawberry yogurt',
  'skim greek yogurt',
  'plain greek yogurt',
  'lowfat greek yoghurt',
  'skim vanilla yoghurt',
  'frozen vanilla yogurt',
  'lowfat vanilla yogurt',
  'skim vanilla greek yogurt',
  'lowfat vanilla greek yogurt',
  'soymilk',
  'soy pulp',
  'lime juic',
  'clamato juice',
  'salt',
  'beer',
  'soy sauce',
  'soybeans',
  'soy flour',
  'soy nuts',
  'soy chunks',
  'soy cheese',
  'soy yogurt',
  'soy protein',
  'soy creamer',
  'soy pudding',
  'soy sausage',
  'soy crumbles',
  'soy margarine',
  'soy lecithin granules',
  'soy butter',
  'soybeans in pods',
  'light soy sauce',
  'sweet soy sauce',
  'dried soybeans',
  'tamari soy sauce',
  'canned soybeans',
  'lowfat soy flour',
  'fat free soy flour',
  'seasoned soy bean paste',
  'red miso soybean paste',
  'dairy nut soy free chocolate chips',
  'low sodium soy sauce',
  'white miso soybean paste',
  'unsweetened soy milk',
  'yellow miso soybean paste',
  'bean curd',
  'bean sprouts',
  'bean threads',
  'bean coffee',
  'bean curd skin',
  'soybeans',
  'mat bean',
  'wax beans',
  'red beans',
  'soybean flour',
  'soybeans in pods',
  'red bean paste',
  'yam bean',
  'potatoes',
  'Shallot',
  'white wine',
  'mustard powder',
  'clams',
  'seasoning packet',
  'littleneck clams',
  'pot roast',
  'Potatoes',
  'salad dressing',
  'corned beef',
  'Parmesan cheese',
  'Parsley',
  'Lime juice',
  'Clamato',
  'Bread crumbs',
  'Beer',
  'Milk',
  'bisquick',
  'clam juice',
  'fava beans',
  'fennel',
  'lima beans',
  'navy beans',
  'flat beans',
  'mung beans',
  'beef broth',
  'chervil',
  'cavatelli',
  'sour cream',
  'olive oil',
  'barbecue sauce',
  'caribbean jerk seasoning',
  'jellybeans',
  'wing bean',
  'guar bean',
  'dill beans',
  'greenbeans',
  'black beans',
  'baked beans',
  'pinto beans',
  'chili beans',
  'white beans',
  'dried beans',
  'mocha beans',
  'black bean sauce',
  'azuki beans',
  'Roman beans',
  'sword beans',
  'canned beans',
  'butter beans',
  'corona beans',
  'cooked bean threads',
  'vanilla bean',
  'refried beans',
  'vanilla bean paste',
  'Miso Soybean Paste',
  'gigante beans',
  'garbanzo beans',
  'garbanzo bean flour',
  'dried soybeans',
  'canelini beans',
  'blackeye beans',
  'yardlong beans',
  'baby lima beans',
  'cranberry beans',
  'raw black beans',
  'canned soybeans',
  'canned red beans',
  'dried navy beans',
  'dried lima beans',
  'split mung bean',
  'dried fava beans',
  'roasted soybeans',
  'chili with beans',
  'canned navy beans',
  'dried pinto beans',
  'canned lima beans',
  'canned fava beans',
  'cooked mung beans',
  'dried Roman beans',
  'dried aduki beans',
  'dried white beans',
  'canned black beans',
  'canned pinto beans',
  'canned white beans',
  'red miso soybean paste',
  'seasoned soybean paste',
  'white kidney beans',
  'dried butter beans',
  'canned Roman beans',
  'dried corona beans',
  'canned azuki beans',
  'cowpea green beans',
  'canned kidney beans',
  'canned butter beans',
  'ground coffee beans',
  'chili without beans',
  'dried gigante beans',
  'canned corona beans',
  'great northern beans',
  'white miso soybean paste',
  'dried garbanzo beans',
  'dried canelini beans',
  'canned gigante beans',
  'canned garbanzo beans',
  'fermented black beans',
  'yellow miso soybean paste',
  'dried baby lima beans',
  'dried cranberry beans',
  'canned canelini beans',
  'frozen baby lima beans',
  'vegetarian baked beans',
  'canned cranberry beans',
  'clams',
  'manila clams',
  'lobster',
  'lobster meat',
  'lobster tails',
  'lobster mushrooms',
  'squat lobster tails',
  'imitation lobster',
  'crab',
  'crabmeat',
  'crab boil',
  'lump crab',
  'fake crab',
  'cooked crab',
  'dungeness crabs',
  'Carrots',
  'Beans',
  'Butternut squash',
  'Lettuce',
  'Beef',
  'Chicken',
  'Sugar',
  'Rabbit',
  'Tomato',
  'Celery',
  'Love',
  'Pepperoni',
  'Flour'
]

unirestIngredientsStrings.sort()

unirestIngredientsStrings = unirestIngredientsStrings.map(str => {
  str = str[0].toUpperCase() + str.slice(1)
  return str
})

const unirestIngredientsStringsSet = new Set(unirestIngredientsStrings)
unirestIngredientsStrings = [...unirestIngredientsStringsSet]

//Here we change an ingredient string into an ingredient object such as {name:'string'}
let unirestIngredients = unirestIngredientsStrings.map(ingredientName => {
  let ingredientObject = {}
  ingredientObject.name = ingredientName
  return ingredientObject
})

//////////////////////////////////////////Recipes////////////////////////////////////////////////

//Get details of recipe based on its ID

// unirest
//   .get(
//     'https://spoonacular-recipe-food-nutrition-v1.p.rapidapi.com/recipes/160906/information'
//   )
//   .header(
//     'X-RapidAPI-Key',
//     '182b450be9mshbb5f865d06b280cp1c805bjsn3b4a55f8187c'
//   )
//   .end(function(result) {
//     console.log(result.status, result.headers, result.body)
//   })

//////////////////////////////
//Get recipes based on stated ingredients

//Sample string
//'https://spoonacular-recipe-food-nutrition-v1.p.rapidapi.com/recipes/findByIngredients?number=10&ranking=1&ingredients=pasta%2C+tomato%2Csausage%2C+basil'

// unirest
//   .get(
//     'https://spoonacular-recipe-food-nutrition-v1.p.rapidapi.com/recipes/findByIngredients?number=10&ranking=1&ingredients=clam'
//   )
//   .header(
//     'X-RapidAPI-Key',
//     '182b450be9mshbb5f865d06b280cp1c805bjsn3b4a55f8187c'
//   )
//   .end(function(result) {
//     console.log(result.status, result.headers, result.body)
//   })

let unirestRecipeIDObjects = []

let unirestRecipeDetails = [
  // {
  //   id: 199412,
  //   title: 'Irish Channel Corned Beef and Cabbage',
  //   readyInMinutes: 45,
  //   servings: 6,
  //   image: 'https://spoonacular.com/recipeImages/199412-556x370.jpg',
  //   imageType: 'jpg',
  //   cuisines: ['european', 'irish'],
  //   dishTypes: ['lunch', 'main course', 'main dish', 'dinner'],
  //   diets: ['gluten free', 'dairy free', 'paleolithic', 'primal', 'whole 30'],
  //   occasions: ['st patricks day'],
  //   winePairing: {},
  //   ingredientsIncluded: '1 each Corned beef, 1/2 cup Onion, 2 cups Chicken broth, 1 each Carrot, 1/2 head Cabbage',
  //   instructions:
  //     'Rinse the corned beef and cut off excess fat.Place the onion on the bottom of the slow cooker.Place the corned beef on top of the onion.Add water, chicken broth, carrots and cabbage.Cook on low heat for 8 to 10 hours, or until meat is cooked and vegetables are tender',
  //   analyzedInstructions: [{name: '', steps: [Array]}],
  //   creditsText: 'Epicurious'
  // },
  {
    id: 626382,
    title: 'Barbecue Beef Stew',
    readyInMinutes: 75,
    servings: 6,
    image: 'https://spoonacular.com/recipeImages/626382-556x370.jpg',
    imageType: 'jpg',
    ingredientsIncluded:
      '2 tbsp Olive oil, 1 each Beef, 1 cup Onions, 1 each Carrot, 2 each Potatoes, 1 cup Barbecue sauce, 1/2 cup Beef broth',
    cuisines: ['bbq', 'barbecu'],
    dishTypes: ['lunch', 'main course', 'main dish', 'dinner'],
    diets: ['gluten free', 'dairy free'],
    occasions: ['fall', "father's day", 'winter'],
    winePairing: {},
    instructions:
      'Add the oil to a large dutch oven. Add salt and pepper to the cubed beef stew meat, then add to the dutch oven and allow the meat to sear on all sides, add in the diced onions and allow the onions to caramelize over low-heat. Add in the rest of the vegetables - carrots and red potatoes.Pour in the barbecue sauce and beef broth and allow the mixture to simmer or medium-low-heat for 1 hour or until the vegetables are tender',
    analyzedInstructions: [{name: '', steps: [Array]}],
    creditsText: 'Gal on a Mission'
  },
  {
    id: 198235,
    title: 'Cook the Book: Perfect Pot Roast',
    readyInMinutes: 45,
    servings: 6,
    image: 'https://spoonacular.com/recipeImages/198235-556x370.jpg',
    imageType: 'jpg',
    ingredientsIncluded:
      '1 tbsp Olive oil, 1 each Beef, 2 each Onions, 1 cup Beef stock, 1 each Carrot',
    cuisines: [],
    dishTypes: ['lunch', 'main course', 'main dish', 'dinner'],
    diets: ['gluten free', 'dairy free', 'paleolithic', 'primal', 'whole 30'],
    occasions: [],
    winePairing: {},
    instructions:
      "Preheat the oven to 275F.  Heat a large pot or Dutch oven over medium-high heat.  Add the olive oil and let it get really hot.  While it heats, prepare the other ingredients.  Generously salt the chuck roast on both sides (I like kosher salt because it adheres more readily to the meat).  Cut a couple of onions in half from root to tip, then cut off the tops and bottoms and peel off the papery skin.  When the pot is very hot, place the onions in the oil and brown on both sides, about a minute per side.  Remove the onions to a plate.  Now, with the burner on high, deglaze the pot by adding 1 cup of the beef stock, whisking constantly.  Throw the carrots into the same (very hot) pot.  Toss them around until slightly brown, about a minute or so.  The point here is to get a nice color started on the outside of the vegetables, not to cook them.  Remove the carrots from the pot and allow the pot to get really hot again.  Add another tablespoon of oil to the pan.  Place the meat in the pot and sear it, about a minute per side.  Now, with the burner on high, deglaze the pot by adding 1 cup of the beef stock, whisking constantly.  The point of deglazing is to loosen all of the burned flavorful bits from the bottom of the pot.  When most of the bits are loosened, place the meat back in the pot.  Followed by the carrots and onions.  Pour enough beef stock into the pot to cover the meat halfway.  Next, put in the fresh rosemary and thyme sprigs.  The fresh herbs absolutely make this dish.  Tuck them into the juice to ensure that the flavors are distributed throughout the pot.  Now, just cover the pot and roast for 3 to 5 hours, depending on the size of your roast. For a 3-pound roast, allow 3 to 3 1/2 hours.  For a 5-pound roast, allow for a 4- to 5-hour cooking time.  Don't disrupt the roast during the cooking process.  When the cooking time is over, check the roast for doneness; a fork should go in easily and the meat should be very tender.  Remove the meat to a cutting board and slice against the grain",
    analyzedInstructions: [{name: '', steps: [Array]}],
    creditsText: 'Serious Eats'
  },
  {
    id: 218244,
    title: 'Roast beef & carrots with easy gravy',
    readyInMinutes: 75,
    servings: 4,
    image: 'https://spoonacular.com/recipeImages/218244-556x370.jpg',
    imageType: 'jpg',
    cuisines: [],
    dishTypes: ['lunch', 'main course', 'main dish', 'dinner'],
    diets: ['dairy free'],
    occasions: [],
    winePairing: {},
    ingredientsIncluded:
      '1 tbsp Mustard powder, 1/2 cup Flour, 1/2 cup Onion, 1/2 cup Carrots, 1 each Beef, 4 each Potatoes',
    instructions:
      'Heat oven to 240C/220C fan/gas 9.Mix the flour and mustard powder withsome seasoning, then rub all over the beef. Put the onion and carrots into a roasting tin and set the beef on top,then cook for 20 mins. Reduce oven to 190C/170C fan/gas 5 and continue to cook the beef for 30 minutes if you like it rare, 40 minutes for medium rare and 1 hr for well done. Remove the beef and carrots from the oven, place onto warm plates or platters and cover with foil to keep warm.Let the beef rest for 30 minutes while you turn up the oven to cook your Yorkshirepuds and finish the potatoes.For the gravy, put the tin with all the meat juices and onions back onto the hob. Stir in the flour, scraping all the stuck bits off the bottom of the tin.Cook for 30 seconds, then slowly stir in the stock, little by little. Bubble to a nice gravy, season, then serve with the beef, carved into slices, carrots and all the other trimmings',
    analyzedInstructions: [{name: '', steps: [Array]}],
    creditsText: 'BBC Good Food'
  },
  // // {
  // //   id: 81789,
  // //   title: 'Roasted Beef Brisket',
  // //   readyInMinutes: 45,
  // //   servings: 10,
  // //   image: 'https://spoonacular.com/recipeImages/81789-556x370.jpg',
  // //   imageType: 'jpg',
  // //   cuisines: ['jewish'],
  // //   dishTypes: ['lunch', 'main course', 'main dish', 'dinner'],
  // //   diets: ['gluten free', 'dairy free'],
  // //   occasions: ['hanukkah'],
  // //   winePairing: {
  // //     pairedWines: ['shiraz', 'tempranillo', 'zinfandel'],
  // //     pairingText:
  // //       "Shiraz, Tempranillo, and Zinfandel are my top picks for Beef Brisket. All these red wines can handle the meaty, smokey flavor of brisket. If you're talking traditional Jewish brisket, you'll want to look for a kosher red wine. The Penfolds Bin 8 Cabernet-Shiraz with a 4.1 out of 5 star rating seems like a good match. It costs about 20 dollars per bottle.",
  // //     productMatches: [[Object]]
  // //   },
  // //   ingredientsIncluded: '',
  // //   instructions: 'No instructions at this time',
  // //   analyzedInstructions: [],
  // //   sourceName: null,
  // //   creditsText: null
  // // },
  {
    id: 368349,
    title: 'Tangy Pot Roast',
    readyInMinutes: 435,
    servings: 6,
    image: 'https://spoonacular.com/recipeImages/368349-556x370.jpg',
    imageType: 'jpg',
    cuisines: [],
    dishTypes: ['lunch', 'main course', 'main dish', 'dinner'],
    diets: ['gluten free', 'dairy free'],
    occasions: [],
    winePairing: {},
    ingredientsIncluded:
      '2 each Potatoes, 1 each Carrot, 1/2 chopped Onion, 1 each Pot roast, 1 cup Salad dressing',
    instructions:
      'Place the potatoes, carrots and onion in a 5-qt slow cooker. Cut roast in half; rub with salt and pepper. Place over vegetables. Combine salad dressing and wine; pour over roast.  Cover and cook on low for 7-8 hours or until meat is tender. Skim fat from cooking juices; thicken juices if desired',
    analyzedInstructions: [{name: '', steps: [Array]}],
    creditsText: 'Taste of Home'
  },
  {
    id: 365817,
    title: "Best Corned Beef 'n' Cabbage",
    readyInMinutes: 55,
    servings: 6,
    image: 'https://spoonacular.com/recipeImages/365817-556x370.jpg',
    imageType: 'jpg',
    cuisines: [],
    dishTypes: ['lunch', 'main course', 'main dish', 'dinner'],
    diets: ['gluten free', 'dairy free', 'whole 30'],
    occasions: [],
    winePairing: {},
    ingredientsIncluded:
      '1 each Corned beef, 1 each Seasoning packet, 2 cups Cabbage, 4 each Potatoes, 1/2 cup Beef broth, 1 each Carrot, 1 cup Onion',
    instructions:
      'In a 6-qt. pressure cooker, combine water and contents of corned beef seasoning packet; add beef. Close cover securely. Turn regulator knob to pressure and select high pressure. Cook for 45 minutes.  Meanwhile, in a large saucepan, combine the cabbage, potatoes and broth. Bring to a boil. Reduce heat; cover and simmer for 10 minutes. Add carrots and onion. Cover and simmer 20-25 minutes longer or until vegetables are tender; drain. Release pressure according to manual instructions. Remove beef to a serving platter. Discard cooking liquid. Serve beef with cabbage, potatoes, carrots and onion',
    analyzedInstructions: [{name: '', steps: [Array]}],
    creditsText: 'Taste of Home'
  },
  /*{
    id: 608865,
    title: 'Penne with Sausage and Roasted Tomatoes',
    readyInMinutes: 65,
    servings: 4,
    image: 'https://spoonacular.com/recipeImages/608865-556x370.jpg',
    imageType: 'jpg',
    cuisines: [],
    dishTypes: ['lunch', 'main course', 'main dish', 'dinner'],
    diets: ['dairy free'],
    occasions: [],
    winePairing: {pairedWines: [], pairingText: '', productMatches: []},

    instructions:
      'Preheat oven to 225 degrees. Line a baking sheet with aluminum foil. Peel 6 cloves garlic and toss with tomatoes, 1 tablespoon olive oil, salt and pepper. Roast on prepared baking sheet in preheated oven for 45 minutes. Remove from oven and set aside. When the there is about 15 minutes left for the tomatoes, bring a large pot of water to boil. Cook pasta according to package directions. Drain but reserve 1/4 cup pasta water. While pasta is cooking, cook sausage in a large skillet over medium high heat until cooked through. Drain and reserve 1 tablespoon pan drippings.Add remaining tablespoon of olive oil to pan drippings. Return sausage to the pan. Add garlic, cook 30 seconds. Add in pasta. Stir. Pour tomatoes, garlic and any pan juices that accumulated on the aluminum foil into the pan. Gently toss to combine. If pasta appears dry, add reserved pasta water. Sprinkle with basil and serve',
    analyzedInstructions: [{name: '', steps: [Array]}],
    creditsText: 'Lifes Ambrosia'
  },
  {
    id: 698664,
    title: 'Fusilli with Lentils, Sausage & Tomatoes',
    readyInMinutes: 25,
    servings: 6,
    image: 'https://spoonacular.com/recipeImages/698664-556x370.jpg',
    imageType: 'jpg',
    cuisines: [],
    dishTypes: ['lunch', 'main course', 'main dish', 'dinner'],
    diets: ['dairy free'],
    occasions: [],
    winePairing: {
      pairedWines: [],
      pairingText:
        'No one wine will suit every pasta dish. Pasta in a tomato-based sauce will usually work well with a medium-bodied red, such as a montepulciano or chianti. Pasta with seafood or pesto will fare better with a light-bodied white, such as a pinot grigio. Cheese-heavy pasta can pair well with red or white - you might try a sangiovese wine for hard cheeses and a chardonnay for soft cheeses. We may be able to make a better recommendation if you ask again with a specific pasta dish.',
      productMatches: []
    },
    instructions:
      'Put a large pot of salted water on to boil.Heat oil in a large skillet over medium heat. Add sausage and cook, breaking up clumps with a fork, until browned, 3 to 5 minutes. Add lentil soup and tomatoes and bring to a simmer. Cook, stirring occasionally, until heated through, about 5 minutes. Stir in basil (or parsley) and season with salt and pepper.Cook pasta until al dente, 8 to 10 minutes. Drain and transfer to a large bowl. Toss with sauce and serve',
    analyzedInstructions: [{name: '', steps: [Array]}],
    creditsText: 'Eating Well'
  },
  {
    id: 535914,
    title: 'Threaded Spaghetti Hot Dog Bites with Homemade Marinara Sauce',
    readyInMinutes: 60,
    servings: 4,
    image: 'https://spoonacular.com/recipeImages/535914-556x370.jpg',
    imageType: 'jpg',
    cuisines: ['american'],
    dishTypes: ['lunch', 'main course', 'main dish', 'dinner'],
    diets: ['dairy free'],
    occasions: [],
    winePairing: {pairedWines: [], pairingText: '', productMatches: []},
    instructions:
      'Heat olive oil in a large pot over low heat. Add the garlic and cook until golden, about 3 minutes. Stir in the basil and tomatoes. Bring to a boil and add the salt; reduce heat to low and simmer, stirring occasionally, until sauce has thickened, about 40-45 minutes. Stir in the balsamic vinegar. Thread 5-7 spaghetti strands through each slice of sausage. In a large pot of boiling salted water, cook pasta according to package instructions; drain well. Serve immediately with marinara sauce',
    analyzedInstructions: [{name: '', steps: [Array]}],
    creditsText: 'Damn Delicious'
  },
  {
    id: 449532,
    title: 'Smoked Sausage with Pasta',
    readyInMinutes: 30,
    servings: 4,
    image: 'https://spoonacular.com/recipeImages/449532-556x370.jpg',
    imageType: 'jpg',
    cuisines: [],
    dishTypes: ['side dish'],
    diets: ['dairy free'],
    occasions: [],
    winePairing: {},
    instructions:
      'Cook pasta according to package directions. Meanwhile, in a large nonstick skillet, saute the sausage, mushrooms, garlic and basil in oil until mushrooms are tender. Drain pasta; add to the sausage mixture. Add the tomatoes, salt and pepper. Toss gently; heat thoroughly',
    analyzedInstructions: [{name: '', steps: [Array]}],
    creditsText: 'Taste of Home'
  },
  {
    id: 161467,
    title: 'Caprese Sausage Pasta Salad',
    readyInMinutes: 90,
    servings: 4,
    image: 'https://spoonacular.com/recipeImages/161467-556x370.jpg',
    imageType: 'jpg',
    cuisines: [],
    dishTypes: ['salad'],
    diets: [],
    occasions: [],
    winePairing: {
      pairedWines: [],
      pairingText:
        'No one wine will suit every pasta dish. Pasta in a tomato-based sauce will usually work well with a medium-bodied red, such as a montepulciano or chianti. Pasta with seafood or pesto will fare better with a light-bodied white, such as a pinot grigio. Cheese-heavy pasta can pair well with red or white - you might try a sangiovese wine for hard cheeses and a chardonnay for soft cheeses. We may be able to make a better recommendation if you ask again with a specific pasta dish.',
      productMatches: []
    },
    instructions:
      'Fill 3-quart saucepan 2/3 full of water and heat to a boil. Add Pasta. Gently boil uncovered for 12 minutes, stirring occasionally; drain.  Rinse with cold water to cool; drain well.  Meanwhile, to toast pine nuts, place in ungreased heavy skillet. Cook over medium heat 3 to 5 minutes, stirring constantly until nuts are light brown.  In large bowl, combine seasoning mix from packet, cold water and oil. Stir in tomatoes, cheese and sausage. Stir in cooked pasta until well mixed. Cover; refrigerate about 1 hour or until chilled; rarnish with pine nuts and basil',
    analyzedInstructions: [{name: '', steps: [Array]}],
    creditsText: 'Betty Crocker'
  },
  {
    id: 535565,
    title: 'One Pot Pasta',
    readyInMinutes: 20,
    servings: 6,
    image: 'https://spoonacular.com/recipeImages/535565-556x370.jpg',
    imageType: 'jpg',
    cuisines: [],
    dishTypes: ['lunch', 'main course', 'main dish', 'dinner'],
    diets: [],
    occasions: [],
    winePairing: {
      pairedWines: [],
      pairingText:
        'No one wine will suit every pasta dish. Pasta in a tomato-based sauce will usually work well with a medium-bodied red, such as a montepulciano or chianti. Pasta with seafood or pesto will fare better with a light-bodied white, such as a pinot grigio. Cheese-heavy pasta can pair well with red or white - you might try a sangiovese wine for hard cheeses and a chardonnay for soft cheeses. We may be able to make a better recommendation if you ask again with a specific pasta dish.',
      productMatches: []
    },
    instructions:
      'In a large stockpot or Dutch oven over medium high heat, combine spaghetti, sausage, onion, tomatoes, basil, garlic and 4 1/2 cups water; season with salt and pepper, to taste. Bring to a boil; reduce heat and simmer, uncovered, until pasta is cooked through and liquid has reduced, about 8-10 minutes. Stir in Parmesan. Serve immediately.',
    analyzedInstructions: [{name: '', steps: [Array]}],
    creditsText: 'Damn Delicious'
  },
  {
    id: 284366,
    title: 'Free-Form Lasagna',
    readyInMinutes: 55,
    servings: 6,
    image: 'https://spoonacular.com/recipeImages/284366-556x370.jpg',
    imageType: 'jpg',
    cuisines: ['mediterranean', 'european', 'italian'],
    dishTypes: ['lunch', 'main course', 'main dish', 'dinner'],
    diets: [],
    occasions: [],
    winePairing: {},
    instructions:
      'Bring a large pot of salted water to boil.Cook sausage in a skillet over medium-high heat, breaking up large pieces, until it loses its pink color, about 5 minutes. Stir in tomatoes, oregano and 1/2 tsp. salt, reduce heat to medium-low and simmer until thick, stirring occasionally, about 20 minutes.  Combine ricotta, Parmesan and basil in a medium microwave-safe bowl.  Add noodles to boiling water; cook until just tender, 10 minutes or as package label directs. Just before noodles are done, microwave ricotta mixture on high for 30 seconds, stirring once. Drain noodles well.  Spread 1 1/2 Tbsp. sauce on each of 4 dinner plates. Place a noodle on top and spread with 1 1/2 Tbsp. cheese mixture. Top with 1 1/2 Tbsp. sauce. Repeat with noodles, cheese mixture and sauce, ending with a layer of sauce. Sprinkle Parmesan on top. Serve, passing additional Parmesan',
    analyzedInstructions: [{name: '', steps: [Array]}],
    creditsText: 'My Recipes'
  },
  {
    id: 161120,
    title: 'Italian Sausage and Pepper Stew',
    readyInMinutes: 25,
    servings: 4,
    image: 'https://spoonacular.com/recipeImages/161120-556x370.jpg',
    imageType: 'jpg',
    cuisines: ['mediterranean', 'european', 'italian'],
    dishTypes: ['lunch', 'main course', 'main dish', 'dinner'],
    diets: [],
    occasions: ['fall', 'winter'],
    winePairing: {},
    instructions:
      'In 6-quart Dutch oven, cook and stir sausage and bell peppers over medium-high heat about 8 minutes or until sausage is no longer pink; drain.  Reduce heat to medium-low. Stir in tomatoes and basil; cover and simmer 10 minutes.  Meanwhile, cook and drain pasta as directed on package. Serve sausage and peppers over cooked pasta; top with cheese',
    analyzedInstructions: [{name: '', steps: [Array]}],
    sourceName: null,
    creditsText: null
  },
  {
    id: 5432,
    title: 'Seasoned Shrimp',
    readyInMinutes: 45,
    servings: 8,
    image: 'https://spoonacular.com/recipeImages/5432-556x370.jpg',
    imageType: 'jpg',
    cuisines: [],
    dishTypes: ['side dish'],
    diets: [
      'gluten free',
      'dairy free',
      'fodmap friendly',
      'whole 30',
      'pescatarian'
    ],
    occasions: [],
    winePairing: {
      pairedWines: ['pinot grigio', 'riesling', 'sauvignon blanc'],
      pairingText:
        'Shrimp can be paired with Pinot Grigio, Riesling, and Sauvignon Blanc. These crisp white wines work well with shrimp prepared in a variety of ways, whether grilled, fried, or in garlic sauce. One wine you could try is Luna Nuda Pinot Grigio. It has 4.4 out of 5 stars and a bottle costs about 14 dollars.',
      productMatches: [[Object]]
    },
    instructions:
      'Heat oil in a large heavy saucepan over high heat. Add shrimp, and cook 1 minute. Stir in stock, seasoning, and lemon juice. Simmer 1 to 2 minutes or until shrimp are just cooked through. Drain; chill.',
    analyzedInstructions: [{name: '', steps: [Array]}],
    creditsText: 'My Recipes'
  },
  {
    id: 882,
    title: 'Vermentino-Braised Sea Bass',
    readyInMinutes: 15,
    servings: 4,
    image: 'https://spoonacular.com/recipeImages/882-556x370.jpg',
    imageType: 'jpg',
    cuisines: [],
    dishTypes: ['lunch', 'main course', 'main dish', 'dinner'],
    diets: [
      'gluten free',
      'dairy free',
      'paleolithic',
      'primal',
      'fodmap friendly',
      'pescatarian'
    ],
    occasions: [],
    winePairing: {
      pairedWines: ['pinot grigio', 'gruener veltliner', 'pinot noir'],
      pairingText:
        "Pinot Grigio, Gruener Veltliner, and Pinot Noir are great choices for Seabass. Fish is as diverse as wine, so it's hard to pick wines that go with every fish. A crisp white wine, such as a pinot grigio or Grüner Veltliner, will suit any delicately flavored white fish. Meaty, strongly flavored fish such as salmon and tuna can even handle a light red wine, such as a pinot noir. One wine you could try is Attems Ramato Pinot Grigio. It has 4.4 out of 5 stars and a bottle costs about 14 dollars",
      productMatches: [[Object]]
    },
    instructions:
      'Using a sharp knife, lightly score the skin of the sea bass fillets in a cross-hatch pattern. Season both sides of the sea bass fillets with salt and pepper, then dust very lightly with flour. In a large skillet, heat 2 tablespoons of the olive oil until almost smoking. Add the sea bass fillets, skin side down, and cook over moderately high heat until browned and crisp, about 3 minutes. Carefully turn the sea bass fillets with a spatula. Pour the white wine into the skillet and add the bay leaves. Cook the fillets over moderate heat until just cooked through, about 2 minutes longer. Transfer the fillets to a warmed platter and cover loosely with aluminum foil.  Add the fish stock or clam juice to the skillet and simmer over moderately high heat until the sauce is slightly reduced, about 2 minutes. Season with salt and stir in the remaining tablespoon of olive oil. Spoon the sauce over the fish and serve',
    analyzedInstructions: [{name: '', steps: [Array]}],
    creditsText: 'Food and Wine'
  },
  {
    id: 474596,
    title: 'Tomato Cream Sauce',
    readyInMinutes: 45,
    servings: 3,
    image: 'https://spoonacular.com/recipeImages/474596-556x370.jpg',
    imageType: 'jpg',
    cuisines: [],
    dishTypes: ['sauce'],
    diets: ['gluten free', 'pescatarian'],
    occasions: [],
    winePairing: {},
    instructions:
      'Add all ingredients except salt to a medium sized saucepan and bring to a boil. Reduce heat and simmer, uncovered and stirring occasionally, for 30-40 minutes, or until sauce has reduced to about 3 cups and the flavour is rich and concentrated.Salt generously to taste',
    analyzedInstructions: [{name: '', steps: [Array]}],
    creditsText: 'The Endless Meal'
  },
  {
    id: 743615,
    title: 'Beer Bloody Marys',
    readyInMinutes: 5,
    servings: 4,
    image: 'https://spoonacular.com/recipeImages/743615-556x370.jpeg',
    imageType: 'jpeg',
    cuisines: [],
    dishTypes: [],
    diets: ['gluten free', 'dairy free', 'pescatarian'],
    occasions: ["father's day"],
    winePairing: {pairedWines: [], pairingText: '', productMatches: []},
    instructions:
      'Combine the lime juice, tomato-clam juice and hot sauce in a pitcher.Mix well and refrigerate until ready to serve.Spread a small amount of salt in a shallow saucer. Moisten the rims of 4 tall glasses with water and dip in the salt. Fill with ice, then fill halfway with the tomato-clam juice mixture. Top with beer and garnish with celery stalks and lime wedges',
    analyzedInstructions: [{name: '', steps: [Array]}],
    creditsText: 'Foodnetwork'
  },*/
  {
    id: 598988,
    title: 'Baked Clams',
    readyInMinutes: 25,
    servings: 2,
    image: 'https://spoonacular.com/recipeImages/598988-556x370.jpg',
    imageType: 'jpg',
    cuisines: [],
    dishTypes: ['side dish'],
    diets: ['pescatarian'],
    occasions: [],
    winePairing: {
      pairedWines: ['chardonnay', 'muscadet', 'riesling'],
      pairingText:
        "Clams on the menu? Try pairing with Chardonnay, Muscadet, and Riesling. Buttery chardonnay is great for scallops, shrimp, crab, and lobster, while muscadet is a classic pick for mussels, oysters, and clams. If you've got some spice in your shellfish, a semi-dry riesling can balance out the heat. The Waterbrook Reserve Chardonnay with a 5 out of 5 star rating seems like a good match. It costs about 20 dollars per bottle.",
      productMatches: [[Object]]
    },
    ingredientsIncluded:
      '2 lbs Clams, 2 cups Bread crumbs, 1/4 cup Parsley, 1/4 cup Parmesan cheese, 2 tbsp Olive oil, 1 cup Clam juice',
    instructions:
      'Preheat the broiler.Open the clams so that they are on the half shell, and set them aside.Mix together the bread crumbs, parsley, Parmesan cheese, olive oil, and clam juice into a semi-dry paste.Spoon and pat the breadcrumb mixture onto each clam. Place them in a broiler pan and put them under the broiler for 5 to 8 minutes or until the breadcrumbs are browned on top',
    analyzedInstructions: [{name: '', steps: [Array]}],
    creditsText: 'Leites Culinaria'
  },
  {
    id: 314071,
    title: 'Beer-Based Bloody Marys',
    readyInMinutes: 25,
    servings: 4,
    image: 'https://spoonacular.com/recipeImages/314071-556x370.jpeg',
    imageType: 'jpeg',
    cuisines: [],
    dishTypes: [],
    diets: ['gluten free', 'dairy free', 'pescatarian'],
    occasions: [],
    winePairing: {pairedWines: [], pairingText: '', productMatches: []},
    ingredientsIncluded:
      '2 ounces Lime juice, 2 cups Clamato juice, 1 oz Salt, 2 cups Beer, 1 stick Celery',
    instructions:
      'Watch how to make this recipe.In a pitcher, combine the lime juice, tomato-clam juice and hot sauce. Mix well and chill until ready to serve.Spread a small amount of salt into a shallow saucer. Moisten the rims of tall glasses and coat them in salt. Fill the glasses with ice and pour in the cocktail.Add the beer and garnish each glass with a celery stick.',
    analyzedInstructions: [{name: '', steps: [Array]}],
    creditsText: 'Foodnetwork'
  },
  {
    id: 180069,
    title: 'Seafood à la King',
    readyInMinutes: 15,
    servings: 6,
    image: 'https://spoonacular.com/recipeImages/180069-556x370.jpg',
    imageType: 'jpg',
    cuisines: [],
    dishTypes: ['side dish'],
    diets: ['gluten free', 'primal', 'pescatarian'],
    occasions: [],
    winePairing: {},
    ingredientsIncluded:
      '1/4 cups Bisquick, 1 cup Milk, 1 can Clams, 1 each Onion, 1 stalk Celery, 2 each Potatoes',
    instructions:
      'Heat oven to 450F.In medium bowl, stir 2 1/4 cups Bisquick mix and the milk until soft dough forms.Drop by 6 spoonfuls onto ungreased cookie sheet.Bake 10 minutes or until golden brown.Meanwhile, in 2-quart saucepan, mix remaining ingredients. Heat to boiling over medium heat, stirring occasionally.To serve, split biscuits in half; place on 6 individual plates. Spoon generous 1/4 cup hot chowder mixture over bottom of each biscuit.Top with remaining biscuit halves. Spoon 1/4 cup chowder mixture over top of each biscuit',
    analyzedInstructions: [{name: '', steps: [Array]}],
    creditsText: 'Betty Crocker'
  },
  {
    id: 609334,
    title: 'Littlenecks in Fennel Broth',
    readyInMinutes: 15,
    servings: 4,
    image: 'https://spoonacular.com/recipeImages/609334-556x370.jpg',
    imageType: 'jpg',
    cuisines: [],
    dishTypes: [],
    diets: [
      'gluten free',
      'dairy free',
      'paleolithic',
      'primal',
      'pescatarian'
    ],
    occasions: [],
    winePairing: {},
    ingredientsIncluded:
      '2 tbsp Olive oil, 1 each Shallot, 1/2 cup Fennel, 2 tbsp White wine, 1 cup Clam juice, 2 lbs Littleneck clams',
    instructions:
      'In a large sauté pan, heat olive oil over medium and add shallots and garlic.Cook one minute.Add fennel and white wine, bring to medium high and cook for another two minutes to reduce the wine a bit.Add clam juice and pepper and cover. Bring to a high simmer and cook for five minutes.Add cleaned little necks and cover (best if the cover is see through so you can watch the clams pop open) cook over high simmer  to a low boil for five minutes. You will see the clams pop open one by one.Once they all pop open (no more than five minutes), with tongs, remove to serving dishes. Discard any clams that did not pop open. Spoon broth and cooked fennel over clams, being careful not to spoon any sediment from the bottom of the pan as some sand will settle there that didn’t get cleaned off.Sprinkle the servings with the fennel fronds',
    analyzedInstructions: [{name: '', steps: [Array]}],
    creditsText: 'A Family Feast '
  },
  {
    id: 388118,
    title: 'New England Clam Chowder',
    readyInMinutes: 15,
    servings: 3,
    image: 'https://spoonacular.com/recipeImages/388118-556x370.jpg',
    imageType: 'jpg',
    cuisines: ['american'],
    dishTypes: ['side dish'],
    diets: ['gluten free', 'primal'],
    occasions: [],
    winePairing: {
      pairedWines: ['chardonnay', 'muscadet', 'riesling'],
      pairingText:
        "Chardonnay, Muscadet, and Riesling are great choices for Clams. Buttery chardonnay is great for scallops, shrimp, crab, and lobster, while muscadet is a classic pick for mussels, oysters, and clams. If you've got some spice in your shellfish, a semi-dry riesling can balance out the heat. You could try Buddha Kat Winery Chardonnay. Reviewers quite like it with a 4 out of 5 star rating and a price of about 25 dollars per bottle.",
      productMatches: [[Object]]
    },
    ingredientsIncluded:
      '1 can Clams, 1/2 cup Onion, 1/2 cup Celery, 1/2 cup Carrots, 2 each Potatoes',
    instructions:
      'In a large saucepan, combine the first five ingredients. Bring to a boil. Reduce heat; cover and simmer for 5 minutes.  Sprinkle with cheese if desired.',
    analyzedInstructions: [{name: '', steps: [Array]}],
    creditsText: 'Taste of Home'
  },
  {
    id: 160906,
    title: 'Creamy Tuna Cavatelli',
    readyInMinutes: 50,
    servings: 4,
    image: 'https://spoonacular.com/recipeImages/160906-556x370.jpg',
    imageType: 'jpg',
    cuisines: [],
    dishTypes: ['lunch', 'main course', 'main dish', 'dinner'],
    diets: ['pescatarian'],
    occasions: [],
    winePairing: {
      pairedWines: [],
      pairingText:
        'No one wine will suit every pasta dish. Pasta in a tomato-based sauce will usually work well with a medium-bodied red, such as a montepulciano or chianti. Pasta with seafood or pesto will fare better with a light-bodied white, such as a pinot grigio. Cheese-heavy pasta can pair well with red or white - you might try a sangiovese wine for hard cheeses and a chardonnay for soft cheeses. We may be able to make a better recommendation if you ask again with a specific pasta dish.',
      productMatches: []
    },
    ingredientsIncluded:
      '1 bag Cavatelli, 1/2 cup Onion, 1 stalk Celery, 1 cup Sour cream',
    instructions:
      'Heat pasta, water, chervil, pepper, vegetables and clam juice to boiling in 10-inch skillet; reduce heat. Cover and simmer 20 to 25 minutes, stirring occasionally, until pasta and vegetables are tender.Stir flour into sour cream dip. Gradually stir sour cream dip, cheese and tuna into pasta mixture. Cook over medium heat, stirring occasionally, until hot',
    analyzedInstructions: [{name: '', steps: [Array]}]
  }
]

let unirestRecipeDetailsFinal = unirestRecipeDetails.map(element => {
  const recipeDetails = {}
  recipeDetails.name = element.title
  recipeDetails.instructions = element.instructions.split('.')
  recipeDetails.description =
    element.cuisines.join('-') + '-' + element.diets.join('-')
  recipeDetails.imageUrl = element.image
  recipeDetails.ingredientsIncluded = whatever(element.ingredientsIncluded)
  return recipeDetails
})

module.exports = {
  unirestIngredients,
  unirestRecipeDetailsFinal
}
