//An ingredients API that supplies recipe, ingredients, etc. information
// const unirest = require('unirest')

// unirest
//   .get(
//     'https://spoonacular-recipe-food-nutrition-v1.p.rapidapi.com/food/ingredients/autocomplete?number=50&query=pars'
//   )
//   .header(
//     'X-RapidAPI-Key',
//     '182b450be9mshbb5f865d06b280cp1c805bjsn3b4a55f8187c'
//   )
//   .end(function(result) {
//     // Useful members are result.status, result.headers, and result.body

//     console.log(result.status, result.headers)
//     const ingredientsObjectsArray = result.body
//     let ingredients = []

//     ingredientsObjectsArray.forEach(element =>
//       ingredients.push(element['name'])
//     )
//     console.log(ingredients)
//   })

////////////////////////////////////////////
//   unirest
//     .get(
//       'https://spoonacular-recipe-food-nutrition-v1.p.rapidapi.com/food/ingredients/autocomplete?number=50&query=carro'
//     )
//     .header(
//       'X-RapidAPI-Key',
//       '182b450be9mshbb5f865d06b280cp1c805bjsn3b4a55f8187c'
//     )
//     .end(async function(result) {
//       // Useful members are result.status, result.headers, and result.body

//       const ingredientsObjectsArray = result.body
//       let ingredients = []

//       ingredientsObjectsArray.forEach(element =>
//         ingredients.push(element['name'])
//       )

//       const ingredientsPromises = ingredients.map(element => {
//         Ingredients.create({
//           name: element
//         })
//       })

//       await Promise.all(ingredientsPromises)
//     })

//////////////////////////////////////////////////
// unirest
//   .get(
//     'https://spoonacular-recipe-food-nutrition-v1.p.rapidapi.com/food/ingredients/autocomplete?number=50&query=carro'
//   )
//   .header(
//     'X-RapidAPI-Key',
//     '182b450be9mshbb5f865d06b280cp1c805bjsn3b4a55f8187c'
//   )
//   .end(async function(result) {
//     // Useful members are result.status, result.headers, and result.body

//     const ingredientsObjectsArray = result.body
//     let ingredients = []

//     ingredientsObjectsArray.forEach(element =>
//       ingredients.push(element['name'])
//     )

//     await db.sync({force: true})
//     console.log('db synced!')

//     ingredients.forEach(async element => {
//       try {
//         await Ingredients.create({
//           name: element
//         })
//       } catch (err) {
//         console.log(
//           `For some reason, the ingredient called ${element} could not be added to the 'Ingredients' table.`
//         )
//       }
//     })

//     console.log('closing db connection')
//     await db.close()
//     console.log('db connection closed')
//   })

let unirestIngredients = [
  'apple',
  'applesauce',
  'apple juice',
  'apple cider',
  'apple jelly',
  'apple butter',
  'apple pie spice',
  'apple pie filling',
  'apple cider vinegar',
  'applewood smoked bacon',
  'red apple',
  'tart apple',
  'gala apple',
  'fuji apple',
  'wood apple',
  'rose apple',
  'star apple',
  'green apple',
  'dried apples',
  'sugar apple',
  'cashew apple',
  'bramley apples',
  'custard apple',
  'braeburn apple',
  'mcintosh apple',
  'pink lady apple',
  'grannysmith apple',
  'red delicious apples',
  'golden delicious apple',
  'beef',
  'beef base',
  'beef broth',
  'beef stock',
  'beef steak',
  'beef gravy',
  'beef bones',
  'beef shank',
  'beef brisket',
  'beef liver',
  'beef franks',
  'beef heart',
  'beef cubes',
  'beef bouillon',
  'beef suet',
  'beef fillet',
  'beef consomme',
  'beef jerky',
  'beef short ribs',
  'beef chuck roast',
  'beef round roast',
  'beef strip loin',
  'beefsteak tomato',
  'beef soup bone',
  'beef bouillon cube',
  'beef top sirloin steak',
  'beef bouillon granules',
  'beef tenderloin steaks',
  'beef shoulder roast',
  'beef ravioli',
  'beef sirloin tip roast',
  'beef-flavor ramen',
  'beef bouillon powder',
  'beef marrow bones',
  'beef patties',
  'beef bone broth',
  'beef kidney',
  'beef stock powder',
  'beefless burger',
  'lean beef',
  'roast beef',
  'mince beef',
  'roast beef deli slices',
  'corned beef',
  'corned beef brisket',
  'ground beef round',
  'cooked beef patty',
  'boneless beef short ribs',
  '85% lean beef',
  '90% lean beef',
  'carrot',
  'carrot juice',
  'carrot tops',
  'carrot quickbread mix',
  'baby carrots',
  'peas and carrots',
  'broccoli carrot cauliflower mix',
  'canned peas and carrots',
  'chicken',
  'chickens',
  'chickpea',
  'chicken meat',
  'chicken legs',
  'chicken base',
  'chicken broth',
  'chicken stock',
  'chicken wings',
  'chicken fat',
  'chicken breast',
  'chicken thighs',
  'chicken parts',
  'chicken gravy',
  'chicken livers',
  'chickpea flour',
  'chicken feet',
  'chicken strips',
  'chicken sausage',
  'chicken cutlets',
  'chicken bones',
  'chicken bouillon',
  'chicken drumsticks',
  'chicken breast halves',
  'chicken seasoning',
  'chicken leg quarters',
  'chicken drumettes',
  'chicken bouillon granules',
  'chicken bouillon powder',
  'chickpea elbows',
  'chicken giblets',
  'chicken mince',
  'chicken brat',
  'chickpea leaf',
  'chicken hearts',
  'chickpea pasta',
  'chickpea penne',
  'chickpea rotini',
  'chicken schmaltz',
  'chickpea spaghetti',
  'desi chickpea',
  'roast chicken',
  'dried chickpeas',
  'baked chicken breast',
  'chunk chicken',
  'split chickpea',
  'canned chickpeas',
  'buffalo chicken sauce',
  'bone in chicken breast halves',
  'bone in chicken breast',
  'duck',
  'duck fat',
  'duck legs',
  'duck breast',
  'duck eggs',
  'duck livers',
  'bombay duck',
  'muscovy duck',
  'egg',
  'eggnog',
  'egg yolk',
  'eggplant',
  'egg white',
  'egg bread',
  'egg noodles',
  'egg beaters',
  'egg replacer',
  'egg substitute',
  'egg roll wrappers',
  'egg white powder',
  'flax egg',
  'chia egg',
  'duck eggs',
  'baby eggplant',
  'quail eggs',
  'Energ egg replacer',
  'cooked egg noodles',
  'poached eggs',
  'chocolate eggs',
  'hardboiled eggs',
  'flour',
  'flounder',
  'flour tortilla',
  'oat flour',
  'cornflour',
  'rye flour',
  'soy flour',
  'cake flour',
  'rice flour',
  'corn flour',
  'masa flour',
  'teff flour',
  'bread flour',
  'spelt flour',
  'besan flour',
  'durum flour',
  'grahm flour',
  'matzo flour',
  'almond flour',
  'pastry flour',
  'quinoa flour',
  'millet flour',
  'peanut flour',
  'wondra flour',
  'barley flour',
  'coconut flour',
  'tapioca flour',
  'sorghum flour',
  'cassava flour',
  'mustard flour',
  'semolina flour',
  'seasoned flour',
  'hazelnut flour',
  'amaranth flour',
  'chestnut flour',
  'buckwheat flour',
  'arrowroot flour',
  'wholemeal flour',
  'grapeseed flour',
  'unbleached flour',
  'brown rice flour',
  'sweet rice flour',
  'lowfat soy flour',
  'self-rising flour',
  'gluten-free flour',
  'high gluten flour',
  'gluten free flour mix',
  'fat free soy flour',
  'malted barley flour',
  'defatted peanut flour',
  'granola',
  'muesli granola',
  'homemade granola',
  'gluten free granola',
  'ham',
  'deli ham',
  'ham bone',
  'ham hock',
  'diced ham',
  'ham steak',
  'cooked ham',
  'smoked ham',
  'boiled ham',
  'serrano ham',
  'graham flour',
  'hamburger bun',
  'graham wafers',
  'hamburger meat',
  'black forest ham',
  'hamburger helper',
  'hamburger patties',
  'graham cracker crust',
  'graham cracker crumbs',
  'graham cracker square',
  'lean ground hamburger',
  'cooked hamburger patty',
  'low fat graham crackers',
  'whole wheat hamburger bun',
  'sesame seed hamburger bun',
  'gluten free hamburger bun',
  'gluten free graham wafers',
  '90% lean ground hamburger',
  'chocolate graham cracker crumbs',
  'gluten-free graham cracker square',
  'ice',
  'iced tea',
  'ice water',
  'ice cream',
  'iceberg lettuce',
  'ice cream cones',
  'iceberg lettuce leaves',
  'ice cream sandwiches',
  'ice-cold booze',
  'rice',
  'rice wine',
  'rice milk',
  'rice chex',
  'rice flour',
  'rice syrup',
  'rice paper',
  'rice vinegar',
  'rice noodles',
  'rice cakes',
  'rice bran oil',
  'rice bran',
  'rice krispies cereal',
  'rice protein powder',
  'juice',
  'Spice Rub',
  'spice mix',
  'juice of lime',
  'juice of lemon',
  'spice cake mix',
  'juice of orange',
  'rice for risotto',
  'juice and zest of 1 lemon',
  'spice drops',
  'juice of meyer lemon',
  '5 spice powder',
  'allspice',
  'licorice twist',
  'verjuice',
  'allspice berries',
  'wild rice',
  'licorice extract',
  'fudge ice cream topping',
  'bbq spice',
  'white rice',
  'brown rice',
  'clam juice',
  'sushi rice',
  'pear juice',
  'black rice',
  'acai juice',
  'jam',
  'jamon',
  'jamon iberico',
  'fig jam',
  'grape jam',
  'cherry jam',
  'apricot jam',
  'dietetic jam',
  'raspberry jam',
  'blueberry jam',
  'pineapple jam',
  'strawberry jam',
  'blackberry jam',
  'lingonberry jam',
  'dietetic grape jam',
  'dietetic cherry jam',
  'dietetic apricot jam',
  'dietetic blueberry jam',
  'dietetic raspberry jam',
  'dietetic strawberry jam',
  'dietetic blackberry jam',
  'kale',
  'lacinato kale',
  'lettuce',
  'lettuce leaf',
  'Cos lettuce',
  'bartlett pear',
  'bibb lettuce',
  'bibb lettuce leaves',
  'lamb lettuce',
  'curly lettuce leaves',
  'curly lettuce',
  'iceberg lettuce leaves',
  'red leaf lettuce',
  'red leaf lettuce leaves',
  'mango',
  'mango puree',
  'mango pulp',
  'mango powder',
  'mango nectar',
  'mango chutney',
  'mango sorbet',
  'mangold',
  'mangosteen',
  'mango extract',
  'dried mango',
  'green mango',
  'nuts',
  'nutmeg',
  'nutella',
  'nut butter',
  'nutritional yeast',
  'nutr-grain cereal',
  'peanut',
  'walnut',
  'peanut oil',
  'walnut oil',
  'peanut sauce',
  'peanut butter',
  'peanut flour',
  'peanut butter cups',
  'peanut butter chips',
  'peanut butter candy',
  'peanut butter cookie mix',
  'coconut',
  'soy nuts',
  'coconut oil',
  'coconut rum',
  'coconut milk',
  'soynut butter',
  'coconut flour',
  'coconut sugar',
  'coconut cream',
  'coconut water',
  'coconut flakes',
  'coconut butter',
  'coconut aminos',
  'coconut extract',
  'coconut meat',
  'coconut vinegar',
  'coconut milk beverage',
  'coconut coffee creamer',
  'coconut milk powder',
  'coconut pecan frosting',
  'chesnut',
  'pine nut',
  'hazelnut',
  'coconut wrap',
  'hazelnut oil',
  'hazelnut meal',
  'hazelnut liqueur',
  'chestnut flour',
  'chestnut mushrooms',
  'hazelnut milk',
  'arecanut',
  'pecan nuts',
  'fresh nutmeg',
  'oil',
  'oil packed tuna',
  'oil cured black olives',
  'oil packed sun dried tomatoes',
  'oil-packed anchovies',
  'oil packed albacore tuna',
  'corn oil',
  'palm oil',
  'hemp oil',
  'flax oil',
  'olive oil',
  'chili oil',
  'salad oil',
  'crab boil',
  'lemon oil',
  'basil oil',
  'olive oil cooking spray',
  'plant oil',
  'sesame oil',
  'peanut oil',
  'walnut oil',
  'garlic oil',
  'almond oil',
  'orange oil',
  'coconut oil',
  'avocado oil',
  'truffle oil',
  'mustard oil',
  'hazelnut oil',
  'london broil',
  'grapeseed oil',
  'sunflower oil',
  'safflower oil',
  'rice bran oil',
  'pistachio oil',
  'vegetable oil spread',
  'vegetable oil shortening',
  'lite olive oil',
  'vegetable oil cooking spray',
  'dark sesame oil',
  'virgin olive oil',
  'packaged no-boil lasagna noodles',
  'extravirgin olive oil',
  'parsley',
  'parsnip',
  'parsley flakes',
  'japanese parsley'
]

unirestIngredients.sort()

const unirestIngredientsSet = new Set(unirestIngredients)
unirestIngredients = [...unirestIngredientsSet]

console.log(unirestIngredients.length)

module.exports = unirestIngredients
