//An ingredients API that supplies recipe, ingredients, etc. information
// const unirest = require('unirest')

/////////////////////////////////Ingredients//////////////////////////////////////
// unirest
//   .get(
//     'https://spoonacular-recipe-food-nutrition-v1.p.rapidapi.com/food/ingredients/autocomplete?number=50&query=orange'
//   )
//   .header(
//     'X-RapidAPI-Key',
//     '182b450be9mshbb5f865d06b280cp1c805bjsn3b4a55f8187c'
//   )
//   .end(function(result) {
//     // Useful members are result.status, result.headers, and result.body

//     console.log(result.status, result.headers)
//     const ingredientsObjectsArray = result.body
//     let ingredients = []

//     ingredientsObjectsArray.forEach(element =>
//       ingredients.push(element['name'])
//     )
//     console.log(ingredients)
//   })

////////////////////////////////////////////
//   unirest
//     .get(
//       'https://spoonacular-recipe-food-nutrition-v1.p.rapidapi.com/food/ingredients/autocomplete?number=50&query=carro'
//     )
//     .header(
//       'X-RapidAPI-Key',
//       '182b450be9mshbb5f865d06b280cp1c805bjsn3b4a55f8187c'
//     )
//     .end(async function(result) {
//       // Useful members are result.status, result.headers, and result.body

//       const ingredientsObjectsArray = result.body
//       let ingredients = []

//       ingredientsObjectsArray.forEach(element =>
//         ingredients.push(element['name'])
//       )

//       const ingredientsPromises = ingredients.map(element => {
//         Ingredients.create({
//           name: element
//         })
//       })

//       await Promise.all(ingredientsPromises)
//     })

//////////////////////////////////////////////////
// unirest
//   .get(
//     'https://spoonacular-recipe-food-nutrition-v1.p.rapidapi.com/food/ingredients/autocomplete?number=50&query=carro'
//   )
//   .header(
//     'X-RapidAPI-Key',
//     '182b450be9mshbb5f865d06b280cp1c805bjsn3b4a55f8187c'
//   )
//   .end(async function(result) {
//     // Useful members are result.status, result.headers, and result.body

//     const ingredientsObjectsArray = result.body
//     let ingredients = []

//     ingredientsObjectsArray.forEach(element =>
//       ingredients.push(element['name'])
//     )

//     await db.sync({force: true})
//     console.log('db synced!')

//     ingredients.forEach(async element => {
//       try {
//         await Ingredients.create({
//           name: element
//         })
//       } catch (err) {
//         console.log(
//           `For some reason, the ingredient called ${element} could not be added to the 'Ingredients' table.`
//         )
//       }
//     })

//     console.log('closing db connection')
//     await db.close()
//     console.log('db connection closed')
//   })

let unirestIngredients = [
  'apple',
  'applesauce',
  'apple juice',
  'apple cider',
  'apple jelly',
  'apple butter',
  'apple pie spice',
  'apple pie filling',
  'apple cider vinegar',
  'applewood smoked bacon',
  'red apple',
  'tart apple',
  'gala apple',
  'fuji apple',
  'wood apple',
  'rose apple',
  'star apple',
  'green apple',
  'dried apples',
  'sugar apple',
  'cashew apple',
  'bramley apples',
  'custard apple',
  'braeburn apple',
  'mcintosh apple',
  'pink lady apple',
  'grannysmith apple',
  'red delicious apples',
  'golden delicious apple',
  'beef',
  'beef base',
  'beef broth',
  'beef stock',
  'beef steak',
  'beef gravy',
  'beef bones',
  'beef shank',
  'beef brisket',
  'beef liver',
  'beef franks',
  'beef heart',
  'beef cubes',
  'beef bouillon',
  'beef suet',
  'beef fillet',
  'beef consomme',
  'beef jerky',
  'beef short ribs',
  'beef chuck roast',
  'beef round roast',
  'beef strip loin',
  'beefsteak tomato',
  'beef soup bone',
  'beef bouillon cube',
  'beef top sirloin steak',
  'beef bouillon granules',
  'beef tenderloin steaks',
  'beef shoulder roast',
  'beef ravioli',
  'beef sirloin tip roast',
  'beef-flavor ramen',
  'beef bouillon powder',
  'beef marrow bones',
  'beef patties',
  'beef bone broth',
  'beef kidney',
  'beef stock powder',
  'beefless burger',
  'lean beef',
  'roast beef',
  'mince beef',
  'roast beef deli slices',
  'corned beef',
  'corned beef brisket',
  'ground beef round',
  'cooked beef patty',
  'boneless beef short ribs',
  '85% lean beef',
  '90% lean beef',
  'carrot',
  'carrot juice',
  'carrot tops',
  'carrot quickbread mix',
  'baby carrots',
  'peas and carrots',
  'broccoli carrot cauliflower mix',
  'canned peas and carrots',
  'chicken',
  'chickens',
  'chickpea',
  'chicken meat',
  'chicken legs',
  'chicken base',
  'chicken broth',
  'chicken stock',
  'chicken wings',
  'chicken fat',
  'chicken breast',
  'chicken thighs',
  'chicken parts',
  'chicken gravy',
  'chicken livers',
  'chickpea flour',
  'chicken feet',
  'chicken strips',
  'chicken sausage',
  'chicken cutlets',
  'chicken bones',
  'chicken bouillon',
  'chicken drumsticks',
  'chicken breast halves',
  'chicken seasoning',
  'chicken leg quarters',
  'chicken drumettes',
  'chicken bouillon granules',
  'chicken bouillon powder',
  'chickpea elbows',
  'chicken giblets',
  'chicken mince',
  'chicken brat',
  'chickpea leaf',
  'chicken hearts',
  'chickpea pasta',
  'chickpea penne',
  'chickpea rotini',
  'chicken schmaltz',
  'chickpea spaghetti',
  'desi chickpea',
  'roast chicken',
  'dried chickpeas',
  'baked chicken breast',
  'chunk chicken',
  'split chickpea',
  'canned chickpeas',
  'buffalo chicken sauce',
  'bone in chicken breast halves',
  'bone in chicken breast',
  'duck',
  'duck fat',
  'duck legs',
  'duck breast',
  'duck eggs',
  'duck livers',
  'bombay duck',
  'muscovy duck',
  'egg',
  'eggnog',
  'egg yolk',
  'eggplant',
  'egg white',
  'egg bread',
  'egg noodles',
  'egg beaters',
  'egg replacer',
  'egg substitute',
  'egg roll wrappers',
  'egg white powder',
  'flax egg',
  'chia egg',
  'duck eggs',
  'baby eggplant',
  'quail eggs',
  'Energ egg replacer',
  'cooked egg noodles',
  'poached eggs',
  'chocolate eggs',
  'hardboiled eggs',
  'flour',
  'flounder',
  'flour tortilla',
  'oat flour',
  'cornflour',
  'rye flour',
  'soy flour',
  'cake flour',
  'rice flour',
  'corn flour',
  'masa flour',
  'teff flour',
  'bread flour',
  'spelt flour',
  'besan flour',
  'durum flour',
  'grahm flour',
  'matzo flour',
  'almond flour',
  'pastry flour',
  'quinoa flour',
  'millet flour',
  'peanut flour',
  'wondra flour',
  'barley flour',
  'coconut flour',
  'tapioca flour',
  'sorghum flour',
  'cassava flour',
  'mustard flour',
  'semolina flour',
  'seasoned flour',
  'hazelnut flour',
  'amaranth flour',
  'chestnut flour',
  'buckwheat flour',
  'arrowroot flour',
  'wholemeal flour',
  'grapeseed flour',
  'unbleached flour',
  'brown rice flour',
  'sweet rice flour',
  'lowfat soy flour',
  'self-rising flour',
  'gluten-free flour',
  'high gluten flour',
  'gluten free flour mix',
  'fat free soy flour',
  'malted barley flour',
  'defatted peanut flour',
  'granola',
  'muesli granola',
  'homemade granola',
  'gluten free granola',
  'ham',
  'deli ham',
  'ham bone',
  'ham hock',
  'diced ham',
  'ham steak',
  'cooked ham',
  'smoked ham',
  'boiled ham',
  'serrano ham',
  'graham flour',
  'hamburger bun',
  'graham wafers',
  'hamburger meat',
  'black forest ham',
  'hamburger helper',
  'hamburger patties',
  'graham cracker crust',
  'graham cracker crumbs',
  'graham cracker square',
  'lean ground hamburger',
  'cooked hamburger patty',
  'low fat graham crackers',
  'whole wheat hamburger bun',
  'sesame seed hamburger bun',
  'gluten free hamburger bun',
  'gluten free graham wafers',
  '90% lean ground hamburger',
  'chocolate graham cracker crumbs',
  'gluten-free graham cracker square',
  'ice',
  'iced tea',
  'ice water',
  'ice cream',
  'iceberg lettuce',
  'ice cream cones',
  'iceberg lettuce leaves',
  'ice cream sandwiches',
  'ice-cold booze',
  'rice',
  'rice wine',
  'rice milk',
  'rice chex',
  'rice flour',
  'rice syrup',
  'rice paper',
  'rice vinegar',
  'rice noodles',
  'rice cakes',
  'rice bran oil',
  'rice bran',
  'rice krispies cereal',
  'rice protein powder',
  'juice',
  'Spice Rub',
  'spice mix',
  'juice of lime',
  'juice of lemon',
  'spice cake mix',
  'juice of orange',
  'rice for risotto',
  'juice and zest of 1 lemon',
  'spice drops',
  'juice of meyer lemon',
  '5 spice powder',
  'allspice',
  'licorice twist',
  'verjuice',
  'allspice berries',
  'wild rice',
  'licorice extract',
  'fudge ice cream topping',
  'bbq spice',
  'white rice',
  'brown rice',
  'clam juice',
  'sushi rice',
  'pear juice',
  'black rice',
  'acai juice',
  'jam',
  'jamon',
  'jamon iberico',
  'fig jam',
  'grape jam',
  'cherry jam',
  'apricot jam',
  'dietetic jam',
  'raspberry jam',
  'blueberry jam',
  'pineapple jam',
  'strawberry jam',
  'blackberry jam',
  'lingonberry jam',
  'dietetic grape jam',
  'dietetic cherry jam',
  'dietetic apricot jam',
  'dietetic blueberry jam',
  'dietetic raspberry jam',
  'dietetic strawberry jam',
  'dietetic blackberry jam',
  'kale',
  'lacinato kale',
  'lettuce',
  'lettuce leaf',
  'Cos lettuce',
  'bartlett pear',
  'bibb lettuce',
  'bibb lettuce leaves',
  'lamb lettuce',
  'curly lettuce leaves',
  'curly lettuce',
  'iceberg lettuce leaves',
  'red leaf lettuce',
  'red leaf lettuce leaves',
  'mango',
  'mango puree',
  'mango pulp',
  'mango powder',
  'mango nectar',
  'mango chutney',
  'mango sorbet',
  'mangold',
  'mangosteen',
  'mango extract',
  'dried mango',
  'green mango',
  'nuts',
  'nutmeg',
  'nutella',
  'nut butter',
  'nutritional yeast',
  'nutr-grain cereal',
  'peanut',
  'walnut',
  'peanut oil',
  'walnut oil',
  'peanut sauce',
  'peanut butter',
  'peanut flour',
  'peanut butter cups',
  'peanut butter chips',
  'peanut butter candy',
  'peanut butter cookie mix',
  'coconut',
  'soy nuts',
  'coconut oil',
  'coconut rum',
  'coconut milk',
  'soynut butter',
  'coconut flour',
  'coconut sugar',
  'coconut cream',
  'coconut water',
  'coconut flakes',
  'coconut butter',
  'coconut aminos',
  'coconut extract',
  'coconut meat',
  'coconut vinegar',
  'coconut milk beverage',
  'coconut coffee creamer',
  'coconut milk powder',
  'coconut pecan frosting',
  'chesnut',
  'pine nut',
  'hazelnut',
  'coconut wrap',
  'hazelnut oil',
  'hazelnut meal',
  'hazelnut liqueur',
  'chestnut flour',
  'chestnut mushrooms',
  'hazelnut milk',
  'arecanut',
  'pecan nuts',
  ' nutmeg',
  'oil',
  'oil packed tuna',
  'oil cured black olives',
  'oil packed sun dried tomatoes',
  'oil-packed anchovies',
  'oil packed albacore tuna',
  'corn oil',
  'palm oil',
  'hemp oil',
  'flax oil',
  'olive oil',
  'chili oil',
  'salad oil',
  'crab boil',
  'lemon oil',
  'basil oil',
  'olive oil cooking spray',
  'plant oil',
  'sesame oil',
  'peanut oil',
  'walnut oil',
  'garlic oil',
  'almond oil',
  'orange oil',
  'coconut oil',
  'avocado oil',
  'truffle oil',
  'mustard oil',
  'hazelnut oil',
  'london broil',
  'grapeseed oil',
  'sunflower oil',
  'safflower oil',
  'rice bran oil',
  'pistachio oil',
  'vegetable oil spread',
  'vegetable oil shortening',
  'lite olive oil',
  'vegetable oil cooking spray',
  'dark sesame oil',
  'virgin olive oil',
  'packaged no-boil lasagna noodles',
  'extravirgin olive oil',
  'parsley',
  'parsnip',
  'parsley flakes',
  'japanese parsley',
  'quinoa',
  'quince',
  'quinoa flour',
  'quinoa flakes',
  'quick cooking oats',
  'quick cooking grits',
  'quick cooking tapioca',
  'quick cooking barley',
  'quinoa pasta',
  'quick-cooking white rice',
  'quick-cooking brown rice',
  'black quinoa',
  'cooked quinoa',
  'carrot quickbread mix',
  'cooked quick oats',
  'cooked quick grits',
  'cooked quick-cooking brown rice',
  ' mint',
  ' dill',
  ' sage',
  ' peas',
  ' corn',
  ' figs',
  ' basil',
  ' thyme',
  ' herbs',
  ' fruit',
  ' ginger',
  ' chives',
  ' yeast',
  ' nutmeg',
  ' parsley',
  ' tuna',
  ' pasta',
  ' ricotta',
  ' cilantro',
  ' rosemary',
  ' tarragon',
  ' marjoram',
  ' bay leaf',
  ' mushrooms',
  ' mozzarella',
  ' chorizo',
  ' green beans',
  ' corn kernels',
  ' bean sprouts',
  ' horseradish',
  ' sardines',
  ' lavender',
  ' epazote',
  ' shiitake mushrooms',
  ' pasta dough',
  ' lasagne sheets',
  ' anchovies',
  ' fenugreek leaves',
  ' herring',
  ' tamarind',
  ' spaghettini',
  ' bulk chorizo',
  'greens',
  'green tea',
  'green peas',
  'green onion',
  'green beans',
  'green chili',
  'green apple',
  'green salsa',
  'green olives',
  'green grapes',
  'green cabbage',
  'green peppers',
  'green tomato',
  'green papaya',
  'green mango',
  'green grams',
  'green tea bags',
  'green food color',
  'green curry paste',
  'green prawns',
  'green cardamoms',
  'green peppercorns',
  'green tea powder',
  'green leaf lettuce',
  'green pesto',
  'green enchilada sauce',
  'green hot sauce',
  'green leaf lettuce leaves',
  'green seedless grapes',
  'green olives with pimentos',
  'beet greens',
  'microgreens',
  'dried green lentils',
  'turnip greens',
  'dried green peas',
  'canned green chiles',
  'cooked green lentils',
  'radish greens',
  'carrot greens',
  'collard greens',
  'mustard greens',
  'cowpea green beans',
  'pickled green beans',
  'chicory greens',
  'pumpkin greens',
  'skinned green gram',
  'dandelion greens',
  'sunflower greens',
  'fiddlehead greens',
  'french style green beans',
  'ramen',
  'caramel',
  'caramel sauce',
  'Caramel Corn',
  'caramelized onions',
  'cooked ramen noodles',
  'beef-flavor ramen',
  'dulce de leche caramel sauce',
  'chocolate covered caramel candy',
  'rice',
  'ricotta',
  'rice wine',
  'rice milk',
  'rice chex',
  'rice flour',
  'rice syrup',
  'rice paper',
  'rice vinegar',
  'rice noodles',
  'rice cakes',
  'rice bran oil',
  'rice bran',
  'rice krispies cereal',
  'rice protein powder',
  'rice for risotto',
  'citric acid',
  'tumeric',
  'wild rice',
  'skim ricotta cheese',
  'white rice',
  'brown rice',
  'sushi rice',
  'black rice',
  'mini ricecakes',
  'turmeric paste',
  'brown rice flour',
  'sweet rice flour',
  'crisp rice cereal',
  'brown rice noodles',
  'crisp rice',
  'cooked rice',
  'minute rice',
  'sticky rice',
  'cooked rice noodles',
  'lowfat ricotta cheese',
  'basmati rice',
  'jasmine rice',
  'miracle rice',
  'non-caloric sweetener',
  'seasoned rice vinegar',
  'glutinous rice',
  'short grain rice',
  'cooked wild rice',
  'cauliflower rice',
  'short brown rice',
  'cooked brown rice',
  'cooked sushi rice',
  'medium grain rice',
  'brown minute rice',
  'salt',
  'salsa',
  'salmon',
  'salami',
  'saltines',
  'salt cod',
  'salad mix',
  'salad oil',
  'salt pork',
  'salsa verde',
  'salmon roe',
  'salted butter',
  'salmon steaks',
  'salad dressing',
  'salted peanuts',
  'salt and pepper',
  'salted cashews',
  'salt packed anchovy',
  'salad shell',
  'salted pork fat',
  'salted sweet butter',
  'no salt added diced tomatoes',
  'sea salt',
  'low salt chicken broth',
  'rock salt',
  'can salmon',
  'fine salt',
  'onion salt',
  'pasta salad mix',
  'ranch salad dressing',
  'asian salad dressing',
  'ranch salad dressing mix',
  'light salad dressing',
  'kosher salt',
  'coarse salt',
  'garlic salt',
  'celery salt',
  'smoked salmon',
  'potato salad',
  'rocket salad',
  'caesar salad dressing',
  'ricotta salata',
  'italian salad dressing mix',
  'roasted salted sunflower nuts',
  'seasoned salt',
  'roasted salted pepitas',
  'catalina salad dressing',
  'raw spiced salmon',
  'vinaigrette salad dressing',
  'dry roasted salted sunflower nuts',
  'tuna',
  'tuna in olive oil',
  'tuna packed in water',
  'ahi tuna',
  'light tuna',
  'fresh tuna',
  'canned tuna',
  'albacore tuna in water',
  'albacore tuna in vegetable oil',
  'yellowfin tuna',
  'unsalted butter',
  'unbleached flour',
  'unsalted peanuts',
  'unsweetened cocoa',
  'unbaked pie shell',
  'unsweetened coconut',
  'unsalted pistachios',
  'unsulfured molasses',
  'unsweetened chocolate',
  'unpopped popcorn',
  'unsweetened applesauce',
  'unseasoned rice vinegar',
  'unsmoked back bacon',
  'unsweetened coconut milk',
  'unsweetened soy milk',
  'unsweetened shredded coconut',
  'unbleached all purpose flour',
  'unsalted pumpkin seeds',
  'unprocessed wheat bran',
  'unsweetened dutch process cocoa powder',
  'uncooked shrimp',
  'sun dried tomato',
  'unsalted sweet butter',
  'sun butter',
  'sun dried tomato pesto',
  'sun dried tomato paste',
  'sun dried tomatoes packed in oil',
  'cajun spice',
  'cajun recipe stewed tomatoes',
  'mesclun',
  'sub bun',
  'brat bun',
  'mini bun',
  'burger bun',
  'hotdog bun',
  'potato bun',
  'pretzel bun',
  'brioche bun',
  'sandwich bun',
  'cinnamon bun',
  'hawaiian bun',
  'ciabatta bun',
  'whole wheat bun',
  'store-bought, uniced cupcakes',
  'gluten free hotdog bun',
  'gluten-free burger bun',
  'whole wheat hotdog bun',
  'vegetable',
  'vegeta',
  'vegenaise',
  'vegan cheese',
  'vegetable oil',
  'veggie patty',
  'vegetable broth',
  'vegetable juice',
  'vegan margarine',
  'vegetarian bacon',
  'veggie lunch meat',
  'vegan sour cream',
  'vegetable shortening',
  'vegan cream cheese',
  'vegan chocolate chips',
  'vegetable stock cube',
  'vegetable oil spread',
  'veggie crumbles',
  'vegan buttery sticks',
  'vegan cheddar cheese',
  'vegetarian baked beans',
  'vegetarian parmesan-style cheese',
  'vegetarian sausages',
  'veggie nuggets',
  'vegan mozzarella',
  'vegetarian sausage',
  'vegetarian meatballs',
  'vegetable tortellini',
  'vegemite',
  'veggie sausage patties',
  'vegetable cooking spray',
  'sea vegetable',
  'root vegetables',
  'asian vegetables',
  'leafy vegetable',
  'textured vegetable protein',
  'butter flavor vegetable shortening',
  'albacore tuna in vegetable oil',
  'wine',
  'wrap',
  'water',
  'wings',
  'wasabi',
  'walnut',
  'wakame',
  'whisky',
  'wieners',
  'wild rice',
  'whole egg',
  'wax beans',
  'whole milk',
  'white wine',
  'white rice',
  'watercress',
  'watermelon',
  'wheat germ',
  'walnut oil',
  'wheat bran',
  'white miso',
  'whitefish',
  'white sugar',
  'white onion',
  'white bread',
  'wood apple',
  'white flour',
  'white corn',
  'white beans',
  'wax chili',
  'wheat chex',
  'wax gourd',
  'white pepper',
  'wine vinegar',
  'wheat beer',
  'whole garlic',
  'wasabi paste',
  'whole turkey',
  'white vinegar',
  'whipped cream',
  'whole chicken',
  'whole cloves',
  'whole almonds',
  'winter squash',
  'wasabi powder',
  'white cheddar',
  'wheat berries',
  'waxy potatoes',
  'white cabbage',
  'wasabi peas',
  'xylitol',
  'xanthan gum',
  'yam',
  'yolk',
  'yuca',
  'yuzu',
  'yeast',
  'yogurt',
  'yukon gold',
  'yuzu juice',
  'yellow onion',
  'yellow miso',
  'yellow squash',
  'yellow mustard',
  'yellow peppers',
  'yellow cornmeal',
  'yellow cake mix',
  'yacon syrup',
  'yellow tomato',
  'yellowfin tuna',
  'young coconut',
  'yard long beans',
  'yellow split peas',
  'yellow wax beans',
  'yellow food color',
  'yellow mustard seeds',
  'yellow cherry tomatoes',
  'yellow curry paste',
  'young coconut meat',
  'yeast rolls',
  'yeast extract spread',
  'yellowtail snapper',
  'yellow corn flour',
  'yuba',
  'yam bean',
  'yuca harina',
  'yellow spice drops',
  'soy yogurt',
  'gf yellow cake mix',
  'food yeast',
  'skim yogurt',
  'greek yogurt',
  'plain yogurt',
  'fresh yeast',
  'sweet yellow onion',
  'lowfat yogurt',
  'frozen yogurt',
  'instant yeast',
  'vanilla yogurt',
  'cooked yellow split peas',
  'brewers yeast',
  'strawberry yogurt',
  'ziti',
  "za'atar",
  'zucchini',
  'zinfandel',
  'zucchini noodles',
  'zest of 1 lemon',
  'zest of 1 orange',
  'zero calorie sweetener',
  'zest and juice of 1 lemon',
  'lime zest',
  'baby zucchini',
  'white zinfandel',
  'cooked ziti',
  'canned zucchini',
  'shiratake ziti',
  'grapefruit zest',
  'blood orange zest',
  'fish',
  'fish sauce',
  'fish stock',
  'fish seasoning',
  'catfish',
  'codfish',
  'redfish',
  'crawfish',
  'monkfish',
  'rockfish',
  'bluefish',
  'goldfish crackers',
  'swordfish',
  'whitefish',
  'monkfish cheeks',
  'thai fish sauce',
  'sablefish',
  'wild fish',
  'carp fish',
  'cuttlefish',
  'ribbon fish',
  'canned fish',
  'tengra fish',
  'Salt Codfish',
  'mackerel fish',
  'pangasius fish',
  'farm raised catfish fillets',
  'herbs',
  'herbes de provence',
  'sherbet',
  'fresh herbs',
  'dried herbs',
  'italian herbs',
  'boursin herb cheese',
  'dill',
  'dill seed',
  'dill pickle',
  'dill pickle relish',
  'dill pickle juice',
  'dill pickle chips',
  'dilly beans',
  'Quesadilla Queso Cheese',
  'granadilla',
  'dried dill',
  'red wine',
  'red miso',
  'red onion',
  'red chile',
  'red apple',
  'red beet',
  'red beans',
  'red plums',
  'red grapes',
  'red hots',
  'red pepper',
  'red potato',
  'red cabbage',
  'red lentils',
  'red snapper',
  'red chard',
  'red jalapeno',
  'red currants',
  'red food color',
  'red curry paste',
  'red grapefruit',
  'red mullet',
  'red wine vinegar',
  'redfish',
  'red bean paste',
  'red chili powder',
  'red chili flakes',
  'red pesto',
  'reduced fat mayo',
  'red leaf lettuce',
  'red pepper powder',
  'red currant jelly',
  'red pepper paste',
  'reduced fat milk',
  'reduced fat cheese',
  'red pearl onions',
  'red enchilada sauce',
  'red delicious apples',
  'red velvet cake mix',
  'reduced fat ice cream',
  'reduced sodium soy sauce',
  'red zinfandel',
  'reduced fat cream cheese',
  'reduced sodium broth',
  'reduced sodium chicken broth',
  'red grapefruit juice',
  'red leaf lettuce leaves',
  'reduced fat shredded cheddar cheese',
  'red-skinned sweet potatoes',
  'red belgian endive',
  'black tea',
  'blackberry',
  'black beans',
  'black rice',
  'black pepper',
  'black olives',
  'black vinegar',
  'blackberry jam',
  'black grapes',
  'black eyed peas',
  'black plums',
  'black walnuts',
  'black tea bags',
  'black cardamoms',
  'black bean sauce',
  'black peppercorns',
  'black quinoa',
  'black treacle',
  'black cod',
  'black forest ham',
  'black lentils',
  'black sesame seeds',
  'black mustard seeds',
  'black cherries',
  'black currants',
  'blackened seasoning',
  'black licorice',
  'blackberry juice',
  'black bass',
  'black drum',
  'black chickpeas',
  'black nightshade',
  'black tiger shrimp',
  'raw black beans',
  'canned black beans',
  'dried blackeye peas',
  'canned black-eyed peas',
  'cooked black lentils',
  'cooked black rice',
  'chinese black mushrooms',
  'salt and black pepper',
  'oil cured black olives',
  'dietetic blackberry jam',
  'fermented black beans',
  'yellow onion',
  'yellow miso',
  'yellow squash',
  'yellow mustard',
  'yellow peppers',
  'yellow cornmeal',
  'yellow cake mix',
  'yellow tomato',
  'yellowfin tuna',
  'yellow split peas',
  'yellow wax beans',
  'yellow food color',
  'yellow mustard seeds',
  'yellow cherry tomatoes',
  'yellow curry paste',
  'yellowtail snapper',
  'yellow corn flour',
  'yellow spice drops',
  'gf yellow cake mix',
  'sweet yellow onion',
  'cooked yellow split peas',
  'blueberry',
  'blue cheese',
  'bluefish',
  'blueberry jam',
  'blue cheese dressing',
  'blue cheese crumbles',
  'blue food coloring',
  'blueberry pie filling',
  'blueberry juice',
  'blueberry jelly',
  'blueberry bagel',
  'wild blueberries',
  'dried blueberries',
  'stilton blue cheese',
  'dietetic blueberry jam',
  'dietetic blueberry jelly',
  'white wine',
  'white rice',
  'white miso',
  'whitefish',
  'white sugar',
  'white onion',
  'white bread',
  'white flour',
  'white corn',
  'white beans',
  'white pepper',
  'white vinegar',
  'white cheddar',
  'white cabbage',
  'white cake mix',
  'white potatoes',
  'white chocolate',
  'white mushrooms',
  'white cornmeal',
  'white grapes',
  'white wine vinegar',
  'white peppercorns',
  'white grape juice',
  'white sesame seeds',
  'white morsels',
  'white asparagus',
  'white balsamic vinegar',
  'white corn tortillas',
  'white whole wheat flour',
  'white salt',
  'white grapefruit',
  'white kidney beans',
  'white sweet potatoes',
  'white zinfandel',
  'white ipa',
  'whitebait',
  'white lentils',
  'white pomfret',
  'white cherries',
  'white seedless grapes',
  'eggwhites',
  'gf white cake mix',
  'egg white powder',
  'solid white tuna packed in water',
  'solid white albacore tuna in olive oil',
  'dried white beans',
  'cooked white rice',
  'canned white beans',
  'dried white kidney beans',
  'canned white kidney beans',
  'orange',
  'orange zest',
  'orange juice',
  'orange oil',
  'orange roughy',
  'orange pepper',
  'orange liqueur',
  'orange bitters',
  'orange gelatin',
  'orange marmalade',
  'orange sections',
  'orange blossom water',
  'orange food coloring',
  'orange juice concentrate',
  'orange tomatoes',
  'navel orange',
  'blood orange',
  'blood orange juice',
  'blood orange zest',
  'candied orange peel',
  'mandarin oranges',
  'mandarin orange segments',
  'red flesh navel orange'
]

unirestIngredients.sort()

const unirestIngredientsSet = new Set(unirestIngredients)
unirestIngredients = [...unirestIngredientsSet]

//////////////////////////////////////////Recipes////////////////////////////////////////////////
//const unirest = require('unirest')

// unirest
//   .get(
//     'https://spoonacular-recipe-food-nutrition-v1.p.rapidapi.com/recipes/findByIngredients?number=10&ranking=1&ingredients=beef%2C+onions%2C+carrots%2C+broth'
//   )
//   .header(
//     'X-RapidAPI-Key',
//     '182b450be9mshbb5f865d06b280cp1c805bjsn3b4a55f8187c'
//   )
//   .end(function(result) {
//     console.log(result.status, result.headers, result.body)
//   })

let unirestRecipeIDObjects = [
  {
    id: 218244,
    title: 'Roast beef & carrots with easy gravy',
    image: 'https://spoonacular.com/recipeImages/218244-312x231.jpg',
    imageType: 'jpg',
    usedIngredientCount: 4,
    missedIngredientCount: 1,
    likes: 243
  },
  {
    id: 198235,
    title: 'Cook the Book: Perfect Pot Roast',
    image: 'https://spoonacular.com/recipeImages/198235-312x231.jpg',
    imageType: 'jpg',
    usedIngredientCount: 4,
    missedIngredientCount: 1,
    likes: 8
  },
  {
    id: 199412,
    title: 'Irish Channel Corned Beef and Cabbage',
    image: 'https://spoonacular.com/recipeImages/199412-312x231.jpg',
    imageType: 'jpg',
    usedIngredientCount: 4,
    missedIngredientCount: 1,
    likes: 0
  },
  {
    id: 626382,
    title: 'Barbecue Beef Stew',
    image: 'https://spoonacular.com/recipeImages/626382-312x231.jpg',
    imageType: 'jpg',
    usedIngredientCount: 4,
    missedIngredientCount: 2,
    likes: 46
  },
  {
    id: 81789,
    title: 'Roasted Beef Brisket',
    image: 'https://spoonacular.com/recipeImages/81789-312x231.jpg',
    imageType: 'jpg',
    usedIngredientCount: 4,
    missedIngredientCount: 2,
    likes: 43
  },
  {
    id: 368349,
    title: 'Tangy Pot Roast',
    image: 'https://spoonacular.com/recipeImages/368349-312x231.jpg',
    imageType: 'jpg',
    usedIngredientCount: 4,
    missedIngredientCount: 2,
    likes: 18
  },
  {
    id: 100753,
    title: 'Melt in Your Mouth Beef Stew',
    image: 'https://spoonacular.com/recipeImages/100753-312x231.jpg',
    imageType: 'jpg',
    usedIngredientCount: 4,
    missedIngredientCount: 2,
    likes: 1
  },
  {
    id: 12436,
    title: 'Beef Stew',
    image: 'https://spoonacular.com/recipeImages/12436-312x231.jpg',
    imageType: 'jpg',
    usedIngredientCount: 4,
    missedIngredientCount: 2,
    likes: 0
  },
  {
    id: 365817,
    title: "Best Corned Beef 'n' Cabbage",
    image: 'https://spoonacular.com/recipeImages/365817-312x231.jpg',
    imageType: 'jpg',
    usedIngredientCount: 4,
    missedIngredientCount: 2,
    likes: 0
  },
  {
    id: 388840,
    title: "Easy Corned Beef 'n' Cabbage",
    image: 'https://spoonacular.com/recipeImages/388840-312x231.jpg',
    imageType: 'jpg',
    usedIngredientCount: 4,
    missedIngredientCount: 2,
    likes: 0
  }
]

// unirest
//   .get(
//     'https://spoonacular-recipe-food-nutrition-v1.p.rapidapi.com/recipes/199412/information'
//   )
//   .header(
//     'X-RapidAPI-Key',
//     '182b450be9mshbb5f865d06b280cp1c805bjsn3b4a55f8187c'
//   )
//   .end(function(result) {
//     console.log(result.status, result.headers, result.body)
//   })

let unirestRecipeDetails = [
  {
    vegetarian: false,
    vegan: false,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    weightWatcherSmartPoints: 13,
    gaps: 'no',
    lowFodmap: false,
    ketogenic: false,
    whole30: true,
    sourceUrl: 'http://www.epicurious.com/recipes/food/views/51224220',
    spoonacularSourceUrl:
      'https://spoonacular.com/irish-channel-corned-beef-and-cabbage-199412',
    aggregateLikes: 0,
    spoonacularScore: 76,
    healthScore: 47,
    creditText: 'Epicurious',
    sourceName: 'Epicurious',
    pricePerServing: 403.93,
    extendedIngredients: [
      {
        id: 11109,
        aisle: 'Produce',
        image: 'cabbage.jpg',
        consitency: 'solid',
        name: 'cabbage',
        original: '1 head cabbage, broken apart',
        originalString: '1 head cabbage, broken apart',
        originalName: 'cabbage, broken apart',
        amount: 1,
        unit: 'head',
        meta: [],
        metaInformation: [],
        measures: [Object]
      },
      {
        id: 11124,
        aisle: 'Produce',
        image: 'sliced-carrot.png',
        consitency: 'solid',
        name: 'carrots',
        original: '4 carrots, chopped',
        originalString: '4 carrots, chopped',
        originalName: 'carrots, chopped',
        amount: 4,
        unit: '',
        meta: [Array],
        metaInformation: [Array],
        measures: [Object]
      },
      {
        id: 6194,
        aisle: 'Canned and Jarred',
        image: 'chicken-broth.png',
        consitency: 'liquid',
        name: 'chicken broth',
        original: '1 14-oz. can chicken broth',
        originalString: '1 14-oz. can chicken broth',
        originalName: 'chicken broth',
        amount: 14,
        unit: 'oz',
        meta: [Array],
        metaInformation: [Array],
        measures: [Object]
      },
      {
        id: 13346,
        aisle: 'Meat',
        image: 'corned-beef.png',
        consitency: 'solid',
        name: 'corned beef',
        original: '3 pounds corned beef',
        originalString: '3 pounds corned beef',
        originalName: 'corned beef',
        amount: 3,
        unit: 'pounds',
        meta: [],
        metaInformation: [],
        measures: [Object]
      },
      {
        id: 11282,
        aisle: 'Produce',
        image: 'brown-onion.png',
        consitency: 'solid',
        name: 'onion',
        original: '1 onion, chopped',
        originalString: '1 onion, chopped',
        originalName: 'onion, chopped',
        amount: 1,
        unit: '',
        meta: [Array],
        metaInformation: [Array],
        measures: [Object]
      },
      {
        id: 14412,
        aisle: 'Beverages',
        image: 'water.png',
        consitency: 'liquid',
        name: 'water',
        original: '1 1/2 cups water',
        originalString: '1 1/2 cups water',
        originalName: 'water',
        amount: 1.5,
        unit: 'cups',
        meta: [],
        metaInformation: [],
        measures: [Object]
      }
    ],
    id: 199412,
    title: 'Irish Channel Corned Beef and Cabbage',
    readyInMinutes: 45,
    servings: 6,
    image: 'https://spoonacular.com/recipeImages/199412-556x370.jpg',
    imageType: 'jpg',
    cuisines: ['european', 'irish'],
    dishTypes: ['lunch', 'main course', 'main dish', 'dinner'],
    diets: ['gluten free', 'dairy free', 'paleolithic', 'primal', 'whole 30'],
    occasions: ['st patricks day'],
    winePairing: {},
    instructions:
      'Rinse the corned beef and cut off excess fat.Place the onion on the bottom of the slow cooker.Place the corned beef on top of the onion.Add water, chicken broth, carrots and cabbage.Cook on low heat for 8 to 10 hours, or until meat is cooked and vegetables are tender',
    analyzedInstructions: [{name: '', steps: [Array]}],
    creditsText: 'Epicurious'
  }
]

let unirestRecipeDetailsFinal = unirestRecipeDetails.map(element => {
  const recipeDetails = {}
  recipeDetails.name = element.title
  recipeDetails.instructions = element.instructions.split('.')
  recipeDetails.description =
    element.cuisines.join('-') + '-' + element.diets.join('-')
  recipeDetails.imageUrl = element.image

  return recipeDetails
})

module.exports = {
  unirestIngredients,
  unirestRecipeDetailsFinal
}
